from pathlib import Path

p = Path('index.html')
text = p.read_text(encoding='utf-8')

def replace_once(old, new, label):
    global text
    if new in text:
        return
    if old not in text:
        raise SystemExit(f'patch target not found: {label}')
    text = text.replace(old, new, 1)

text = text.replace('<title>심연 회수대 - v1.4 방/복도/문 프로토타입</title>', '<title>심연 회수대 - v1.8 전투/장비 업데이트</title>')
text = text.replace('• 몬스터는 시간이 지나면 재생성', '• 몬스터는 층을 이동할 때 다시 재생성')
if '• 던전 안에서도 가방의 무기를 즉시 장착 가능' not in text:
    text = text.replace('• 몬스터는 층을 이동할 때 다시 재생성<br>', '• 몬스터는 층을 이동할 때 다시 재생성<br>• 던전 안에서도 가방의 무기를 즉시 장착 가능<br>')
if '.equipMini{' not in text:
    text = text.replace('.lootEntry{display:grid;grid-template-columns:1fr auto;gap:6px;padding:7px 0;border-bottom:1px solid #29333f}', '.lootEntry{display:grid;grid-template-columns:1fr auto;gap:6px;padding:7px 0;border-bottom:1px solid #29333f}.equipMini{margin-top:5px;padding:4px 6px;font-size:10px;width:100%}.slot.weaponSlot{border-color:#435468}.slot.weaponSlot:hover{border-color:#6b86a5}')

replace_once(
"function renderStash(){const g=$('#stashGrid');g.innerHTML='';if(!profile.stash.length)g.innerHTML='<div class=\"muted\">창고가 비어 있습니다.</div>';profile.stash.forEach((it,i)=>{const d=document.createElement('div');d.className='slot';d.innerHTML=itemHTML(it);g.appendChild(d)})}",
"function renderStash(){const g=$('#stashGrid');g.innerHTML='';if(!profile.stash.length)g.innerHTML='<div class=\"muted\">창고가 비어 있습니다.</div>';profile.stash.forEach((it,i)=>{const d=document.createElement('div');d.className='slot'+(it.kind==='weapon'?' weaponSlot':'');d.innerHTML=itemHTML(it);if(it.kind==='weapon'){const b=document.createElement('button');b.className='equipMini';b.textContent='장착';b.onclick=()=>equipLobbyWeapon(i);d.appendChild(b)}g.appendChild(d)})}\nfunction cleanWeaponItem(w){const c=JSON.parse(JSON.stringify(w));delete c._fromProfile;delete c._profileType;c.kind='weapon';return c}\nfunction equipLobbyWeapon(i){const it=profile.stash[i];if(!it||it.kind!=='weapon')return;if(it.durability<=0)return toast('파손된 장비는 장착할 수 없습니다.');const old=profile.weapons[it.type];profile.weapons[it.type]=cleanWeaponItem(it);profile.stash.splice(i,1);if(old)profile.stash.push(cleanWeaponItem(old));profile.selected=it.type;save();renderLobby();toast(it.name+' 장착 완료.')}",
'renderStash')

replace_once(
"function startRun(){const w=profile.weapons[profile.selected];if(!w||w.durability<=0)return toast('선택 장비가 파손되었습니다. 수리하세요.');const take={arrow:Math.min(profile.ammo.arrow,30),mana:Math.min(profile.ammo.mana,90),bullet:Math.min(profile.ammo.bullet,24)};Object.keys(take).forEach(k=>profile.ammo[k]-=take[k]);const pots=Math.min(profile.potions,3);profile.potions-=pots;const scrolls=Math.min(profile.scrolls,1);profile.scrolls-=scrolls;save();run={floor:1,moves:0,hp:100,maxHp:100,stam:100,weapon:JSON.parse(JSON.stringify(w)),ammo:take,potions:pots,scrolls,inv:[],floorStates:{},player:{x:0,y:0,r:11,dirX:1,dirY:0},enemies:[],shots:[],enemyShots:[],attackCd:0,cast:0,block:false,lastHit:0,spawnTimer:0,castReturn:0,castStartPos:null,interact:null,near:null,swing:0,swingMax:0,swingType:null,swingAngle:0,attackCdMax:0,chargeType:null,chargeTime:0,chargeMax:0,magicTarget:null,magicFx:0,magicFxX:0,magicFxY:0,chestOpening:null,coins:0,keys:0,groundLoot:[],rollTimer:0,rollCd:0,rollX:0,rollY:0};loadFloor(1,true,'start');$('#lobbyView').classList.add('hidden');$('#dungeonView').classList.remove('hidden');log('B1에 진입했습니다. 닫힌 문 너머는 보이지 않습니다. 방을 하나씩 확인해 아래층 계단을 찾으세요.');renderRunUI();canvas.parentElement.focus()}",
"function startRun(){const w=profile.weapons[profile.selected];if(!w||w.durability<=0)return toast('선택 장비가 파손되었습니다. 수리하세요.');const take={arrow:Math.min(profile.ammo.arrow,30),mana:Math.min(profile.ammo.mana,90),bullet:Math.min(profile.ammo.bullet,24)};Object.keys(take).forEach(k=>profile.ammo[k]-=take[k]);const pots=Math.min(profile.potions,3);profile.potions-=pots;const scrolls=Math.min(profile.scrolls,1);profile.scrolls-=scrolls;save();const carried=JSON.parse(JSON.stringify(w));carried.kind='weapon';carried._fromProfile=true;carried._profileType=profile.selected;run={floor:1,moves:0,hp:100,maxHp:100,stam:100,weapon:carried,ammo:take,potions:pots,scrolls,inv:[],floorStates:{},player:{x:0,y:0,r:11,dirX:1,dirY:0},enemies:[],shots:[],enemyShots:[],enemyAreas:[],attackCd:0,cast:0,block:false,lastHit:0,castReturn:0,castStartPos:null,interact:null,near:null,swing:0,swingMax:0,swingType:null,swingAngle:0,attackCdMax:0,chargeType:null,chargeTime:0,chargeMax:0,magicTarget:null,magicFx:0,magicFxX:0,magicFxY:0,chestOpening:null,coins:0,keys:0,groundLoot:[],rollTimer:0,rollCd:0,rollX:0,rollY:0};loadFloor(1,true,'start');$('#lobbyView').classList.add('hidden');$('#dungeonView').classList.remove('hidden');log('B1에 진입했습니다. 이 층의 몬스터는 모두 배치되었습니다. 층을 이동하면 다시 나타납니다.');renderRunUI();canvas.parentElement.focus()}",
'startRun')

replace_once(
"function loadFloor(f,first=false,entry='up'){run.floor=f;if(!run.floorStates[f])run.floorStates[f]=genFloorState(f);const st=run.floorStates[f];run.enemies=[];run.shots=[];run.enemyShots=[];run.groundLoot=[];run.chestOpening=null;const pos=first||entry==='up'?st.upPos:st.downPos;run.player.x=pos.x+(entry==='down'?-38:38);run.player.y=pos.y;spawnWave(true);run.spawnTimer=0;closeLoot();syncMouseWorld();renderRunUI();if(!first)log(`B${f} 이동. 누적 층 이동 ${run.moves}회. 방과 복도를 탐색해 계단을 찾으세요.`)}",
"function loadFloor(f,first=false,entry='up'){run.floor=f;if(!run.floorStates[f])run.floorStates[f]=genFloorState(f);const st=run.floorStates[f];run.enemies=[];run.shots=[];run.enemyShots=[];run.enemyAreas=[];run.groundLoot=[];run.chestOpening=null;const pos=first||entry==='up'?st.upPos:st.downPos;run.player.x=pos.x+(entry==='down'?-38:38);run.player.y=pos.y;spawnWave(true);closeLoot();syncMouseWorld();renderRunUI();if(!first)log(`B${f} 이동. 몬스터가 다시 배치되었습니다. 누적 층 이동 ${run.moves}회.`)}",
'loadFloor')

replace_once(
"function renderRunUI(){if(!run)return;const th=floorTheme(run.floor);$('#floorHud').textContent=`B${run.floor} · ${th[0]}`;$('#moveHud').textContent=`층 이동 ${run.moves}`;const lv=instability();$('#instabilityHud').textContent=['안정','불안정 I','불안정 II','불안정 III','심연 폭주'][lv];$('#weaponHud').textContent=weaponDefs[run.weapon.type].icon+' '+weaponDefs[run.weapon.type].name;$('#hpText').textContent=`${Math.ceil(run.hp)}/${run.maxHp}`;$('#hpBar').style.width=Math.max(0,run.hp/run.maxHp*100)+'%';$('#stamText').textContent=Math.ceil(run.stam);$('#stamBar').style.width=run.stam+'%';$('#ammoHud').innerHTML=`🏹 ${run.ammo.arrow} · 🔮 ${run.ammo.mana} · 🔫 ${run.ammo.bullet}<br>🧪 ${run.potions} · 📜 ${run.scrolls}<br>💰 원정 ${run.coins}G · 🗝 ${run.keys}<br>⬆ 탈출까지 ${Math.max(0,run.floor-1)}층 · 내구 ${run.weapon.durability}/${run.weapon.maxDurability}`;$('#invCount').textContent=run.inv.length;$('#runValue').textContent=money(run.coins+run.inv.reduce((a,b)=>a+(b.value||0),0));const g=$('#runInv');g.innerHTML='';for(let i=0;i<12;i++){const s=document.createElement('div');s.className='slot';s.innerHTML=run.inv[i]?itemHTML(run.inv[i]):'';g.appendChild(s)}$('#goldTop').textContent=money(profile.gold)}",
"function renderRunUI(){if(!run)return;const th=floorTheme(run.floor);$('#floorHud').textContent=`B${run.floor} · ${th[0]}`;$('#moveHud').textContent=`층 이동 ${run.moves}`;const lv=instability();$('#instabilityHud').textContent=['안정','불안정 I','불안정 II','불안정 III','심연 폭주'][lv];$('#weaponHud').textContent=weaponDefs[run.weapon.type].icon+' '+run.weapon.name;$('#hpText').textContent=`${Math.ceil(run.hp)}/${run.maxHp}`;$('#hpBar').style.width=Math.max(0,run.hp/run.maxHp*100)+'%';$('#stamText').textContent=Math.ceil(run.stam);$('#stamBar').style.width=run.stam+'%';$('#ammoHud').innerHTML=`🏹 ${run.ammo.arrow} · 🔮 ${run.ammo.mana} · 🔫 ${run.ammo.bullet}<br>🧪 ${run.potions} · 📜 ${run.scrolls}<br>💰 원정 ${run.coins}G · 🗝 ${run.keys}<br>⬆ 탈출까지 ${Math.max(0,run.floor-1)}층 · 장착 ${run.weapon.name}<br>공격 ${run.weapon.damage} · 내구 ${run.weapon.durability}/${run.weapon.maxDurability}`;$('#invCount').textContent=run.inv.length;$('#runValue').textContent=money(run.coins+run.inv.reduce((a,b)=>a+(b.value||0),0));const g=$('#runInv');g.innerHTML='';for(let i=0;i<12;i++){const s=document.createElement('div'),it=run.inv[i];s.className='slot'+(it&&it.kind==='weapon'?' weaponSlot':'');s.innerHTML=it?itemHTML(it):'';if(it&&it.kind==='weapon'){const b=document.createElement('button');b.className='equipMini';b.textContent='장착';b.disabled=it.durability<=0;b.onclick=()=>equipRunWeapon(i);s.appendChild(b)}g.appendChild(s)}$('#goldTop').textContent=money(profile.gold)}\nfunction equipRunWeapon(i){if(!run)return;const it=run.inv[i];if(!it||it.kind!=='weapon')return;if(it.durability<=0)return toast('파손된 장비는 장착할 수 없습니다.');if(run.cast>0||run.chargeType||run.rollTimer>0||run.chestOpening)return toast('지금은 장비를 교체할 수 없습니다.');cancelCharge();run.block=false;const old=run.weapon;run.weapon=it;run.inv[i]=old;run.attackCd=Math.max(run.attackCd,.28);log(`${it.name} 장착. ${weaponDefs[it.type].name}으로 교체했습니다.`);renderRunUI()}",
'renderRunUI')

replace_once(
"function escapeRun(viaScroll=false){profile.gold+=run.coins;run.inv.forEach(it=>{if(it.kind==='material'){profile.materials[it.material]=(profile.materials[it.material]||0)+it.qty}else profile.stash.push(it)});profile.ammo.arrow+=run.ammo.arrow;profile.ammo.mana+=run.ammo.mana;profile.ammo.bullet+=run.ammo.bullet;profile.potions+=run.potions;profile.scrolls+=run.scrolls;profile.weapons[run.weapon.type].durability=run.weapon.durability;save();toast(viaScroll?'귀환 성공! 전리품을 회수했습니다.':'B1 탈출 성공! 전리품을 회수했습니다.');endRun(false)}\nfunction endRun(lost=true){if(lost)profile.weapons[run.weapon.type].durability=Math.max(0,run.weapon.durability);save();run=null;$('#dungeonView').classList.add('hidden');$('#lobbyView').classList.remove('hidden');closeLoot();renderLobby()}",
"function restoreCarriedProfileGear(){if(!run)return;const all=[run.weapon,...run.inv];for(const it of all){if(it&&it.kind==='weapon'&&it._fromProfile&&it._profileType){profile.weapons[it._profileType]=cleanWeaponItem(it)}}}\nfunction escapeRun(viaScroll=false){profile.gold+=run.coins;restoreCarriedProfileGear();const currentIsLoot=run.weapon&&run.weapon.kind==='weapon'&&!run.weapon._fromProfile;for(const it of run.inv){if(it.kind==='material'){profile.materials[it.material]=(profile.materials[it.material]||0)+it.qty}else if(it.kind==='weapon'){if(!it._fromProfile)profile.stash.push(cleanWeaponItem(it))}else profile.stash.push(it)}if(currentIsLoot){const old=profile.weapons[run.weapon.type];if(old)profile.stash.push(cleanWeaponItem(old));profile.weapons[run.weapon.type]=cleanWeaponItem(run.weapon);profile.selected=run.weapon.type}else if(run.weapon&&run.weapon._fromProfile){profile.weapons[run.weapon._profileType]=cleanWeaponItem(run.weapon);profile.selected=run.weapon.type}profile.ammo.arrow+=run.ammo.arrow;profile.ammo.mana+=run.ammo.mana;profile.ammo.bullet+=run.ammo.bullet;profile.potions+=run.potions;profile.scrolls+=run.scrolls;save();toast(viaScroll?'귀환 성공! 전리품과 장비를 회수했습니다.':'B1 탈출 성공! 전리품과 장비를 회수했습니다.');endRun(false)}\nfunction endRun(lost=true){if(lost)restoreCarriedProfileGear();save();run=null;$('#dungeonView').classList.add('hidden');$('#lobbyView').classList.remove('hidden');closeLoot();renderLobby()}",
'escapeRun/endRun')

replace_once(
"function fireEnemy(e,kind){const a=Math.atan2(run.player.y-e.y,run.player.x-e.x),sp=kind==='mage'?230:kind==='bomb'?190:kind==='sniper'?620:330;run.enemyShots.push({x:e.x,y:e.y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,r:kind==='mage'?7:kind==='bomb'?8:4,kind,damage:enemyTypes[e.type].damage,life:kind==='bomb'?1.15:2})}",
"function fireEnemy(e,kind){const a=Math.atan2(run.player.y-e.y,run.player.x-e.x),sp=kind==='bomb'?190:kind==='sniper'?620:330;run.enemyShots.push({x:e.x,y:e.y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,r:kind==='bomb'?8:4,kind,damage:enemyTypes[e.type].damage,life:kind==='bomb'?1.15:2})}\nfunction lineBlocked(x1,y1,x2,y2){const obs=getCollisionRects(run.floorStates[run.floor]),dist=Math.hypot(x2-x1,y2-y1),steps=Math.ceil(dist/14);for(let i=1;i<steps;i++){const t=i/steps,x=x1+(x2-x1)*t,y=y1+(y2-y1)*t;if(rectCollide(x,y,3,obs))return true}return false}\nfunction castEnemyArea(e,damage,radius=76,delay=.95,label='저주 마법'){if(!run.enemyAreas)run.enemyAreas=[];const tx=run.player.x,ty=run.player.y;if(lineBlocked(e.x,e.y,tx,ty))return false;run.enemyAreas.push({x:tx,y:ty,r:radius,time:delay,max:delay,damage,label,exploded:false,blast:0});return true}\nfunction updateEnemyAreas(dt){if(!run.enemyAreas)return;for(const a of run.enemyAreas){if(!a.exploded){a.time-=dt;if(a.time<=0){a.exploded=true;a.blast=.24;if(Math.hypot(run.player.x-a.x,run.player.y-a.y)<=a.r+run.player.r)damagePlayer(a.damage,a.label,'mage');run.shake=Math.max(run.shake||0,4)}}else a.blast-=dt}run.enemyAreas=run.enemyAreas.filter(a=>!a.exploded||a.blast>0)}",
'enemy area helpers')

text = text.replace(" const lv=instability();run.spawnTimer+=dt;if(run.spawnTimer>Math.max(5,13-lv*1.5)){run.spawnTimer=0;spawnWave(false);log('던전의 방 어딘가에서 몬스터가 다시 나타났습니다.')}\n updateEnemies(dt);updateShots(dt);", " updateEnemyAreas(dt);\n updateEnemies(dt);updateShots(dt);")
text = text.replace("else if(e.type==='mage'){if(dist<220)tryMoveEnt(e,-dx0/dist*d.speed*dt,-dy0/dist*d.speed*dt);else if(dist>360)tryMoveEnt(e,ux*d.speed*.7*dt,uy*d.speed*.7*dt);if(e.cd<=0&&dist<500){fireEnemy(e,'mage');e.cd=2.2}}", "else if(e.type==='mage'){if(dist<220)tryMoveEnt(e,-dx0/dist*d.speed*dt,-dy0/dist*d.speed*dt);else if(dist>360)tryMoveEnt(e,ux*d.speed*.7*dt,uy*d.speed*.7*dt);if(e.cd<=0&&dist<500){if(castEnemyArea(e,d.damage,82,1.0,'저주 장판'))e.cd=2.45;else e.cd=.35}}")
text = text.replace("if(e.cd<=0&&dist<360){fireEnemy(e,'mage');e.cd=2.5}}", "if(e.cd<=0&&dist<360){if(castEnemyArea(e,d.damage+2,70,1.15,'소환술사의 마법진'))e.cd=2.8;else e.cd=.4}}")

if 'for(const a of run.enemyAreas||[])' not in text:
    old = " for(const s of run.enemyShots){if(!isPointVisible(st,s.x,s.y))continue;ctx.fillStyle=s.kind==='mage'?'#b56bd2':s.kind==='bomb'?'#d17a45':s.kind==='sniper'?'#ff6b6b':'#c2a873';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}"
    new = " for(const a of run.enemyAreas||[]){if(!isPointVisible(st,a.x,a.y))continue;if(!a.exploded){const q=1-Math.max(0,a.time)/a.max;ctx.fillStyle='rgba(173,74,208,.16)';ctx.beginPath();ctx.arc(a.x,a.y,a.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(220,128,245,.95)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(a.x,a.y,a.r,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='rgba(255,190,255,.95)';ctx.lineWidth=4;ctx.beginPath();ctx.arc(a.x,a.y,a.r,-Math.PI/2,-Math.PI/2+Math.PI*2*q);ctx.stroke()}else{const q=Math.max(0,a.blast/.24);ctx.fillStyle=`rgba(203,105,235,${.28*q})`;ctx.beginPath();ctx.arc(a.x,a.y,a.r*(1.08-q*.08),0,Math.PI*2);ctx.fill();ctx.strokeStyle=`rgba(242,188,255,${q})`;ctx.lineWidth=7*q+1;ctx.beginPath();ctx.arc(a.x,a.y,a.r*(1.05-q*.05),0,Math.PI*2);ctx.stroke()}}\n for(const s of run.enemyShots){if(!isPointVisible(st,s.x,s.y))continue;ctx.fillStyle=s.kind==='bomb'?'#d17a45':s.kind==='sniper'?'#ff6b6b':'#c2a873';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}"
    if old not in text:
        raise SystemExit('patch target not found: enemy magic draw')
    text = text.replace(old, new, 1)

text = text.replace('방과 복도를 탐색 · SPACE 구르기 · 닫힌 문 너머는 보이지 않음 · E 상호작용', '방과 복도를 탐색 · SPACE 구르기 · 가방 무기는 장착 버튼으로 교체 · E 상호작용')

p.write_text(text, encoding='utf-8')
print('game patch applied')
