from pathlib import Path


def rep(text, old, new, label):
    if old not in text:
        raise SystemExit(f'missing anchor: {label}')
    return text.replace(old, new, 1)

# ---------- simulation ----------
p = Path('src/sim.js')
s = p.read_text(encoding='utf-8')

s = rep(s, "export const GEAR={\n armor_light:{kind:'armor',name:'경량 방탄복',price:480,armor:45,maxArmor:45},\n armor_heavy:{kind:'armor',name:'중형 방탄복',price:880,armor:72,maxArmor:72},\n helmet:{kind:'helmet',name:'방탄 헬멧',price:360,durability:35,maxDurability:35},\n backpack:{kind:'backpack',name:'전술 백팩',price:420,capacity:12},\n med:{kind:'med',name:'IFAK 치료키트',price:160,heal:45},\n grenade:{kind:'grenade',name:'M67 수류탄',price:240,damage:92,radius:165}\n};\n",
"export const GEAR={\n armor_light:{kind:'armor',name:'경량 방탄복',price:480,armor:45,maxArmor:45},\n armor_heavy:{kind:'armor',name:'중형 방탄복',price:880,armor:72,maxArmor:72},\n helmet:{kind:'helmet',name:'방탄 헬멧',price:360,durability:35,maxDurability:35},\n backpack:{kind:'backpack',name:'전술 백팩',price:420,capacity:12},\n med:{kind:'med',name:'IFAK 치료키트',price:160,heal:45},\n grenade:{kind:'grenade',name:'M67 수류탄',price:240,damage:92,radius:165}\n};\n\nexport const WEAPON_PARTS={\n optic_2x:{kind:'part',key:'optic_2x',slot:'optic',name:'2× 전술 조준경',price:420,compatible:['smg','ar','dmr'],visionBonus:2,viewLead:120},\n optic_4x:{kind:'part',key:'optic_4x',slot:'optic',name:'4× 정밀 조준경',price:760,compatible:['ar','dmr'],visionBonus:4,viewLead:220},\n ext_mag:{kind:'part',key:'ext_mag',slot:'mag',name:'확장 탄창',price:390,compatible:['pistol','smg','ar','dmr'],magMult:1.4},\n shell_tube:{kind:'part',key:'shell_tube',slot:'mag',name:'연장 튜브',price:340,compatible:['shotgun'],magBonus:2},\n vertical_grip:{kind:'part',key:'vertical_grip',slot:'grip',name:'수직 손잡이',price:360,compatible:['smg','ar','dmr'],spreadMult:.68,recoilMult:.72}\n};\n\nexport function weaponAcceptsPart(weapon,part){const d=part?.key?WEAPON_PARTS[part.key]:part;if(!weapon||weapon.kind!=='weapon'||!d)return false;return (d.compatible||[]).includes(weapon.type)}\nexport function weaponPartEffects(weapon){const out={spreadMult:1,recoilMult:1,magMult:1,magBonus:0,visionBonus:0,viewLead:0};for(const part of Object.values(weapon?.parts||{})){const d=part?.key?WEAPON_PARTS[part.key]:null;if(!d)continue;if(d.spreadMult)out.spreadMult*=d.spreadMult;if(d.recoilMult)out.recoilMult*=d.recoilMult;if(d.magMult)out.magMult*=d.magMult;if(d.magBonus)out.magBonus+=d.magBonus;if(d.visionBonus)out.visionBonus+=d.visionBonus;if(d.viewLead)out.viewLead=Math.max(out.viewLead,d.viewLead)}return out}\nexport function weaponMagCapacity(weapon){if(!weapon?.type||!WEAPONS[weapon.type])return 0;const d=WEAPONS[weapon.type],e=weaponPartEffects(weapon);return Math.max(1,Math.round(d.mag*e.magMult+e.magBonus))}\n", 'parts constants')

s = rep(s, "  id:'harbor',name:'침수 항만 09',palette:MAP_PALETTES.harbor,",
"  id:'harbor',name:'침수 항만 09',trait:'침수 항만 · 넓은 사선 / 물속 이동 둔화',visionMod:1,waterPassable:true,waterSpeed:.62,dynamicCoverBase:18,lootProfile:'harbor',palette:MAP_PALETTES.harbor,", 'harbor traits')
s = rep(s, "  id:'research',name:'오로라 폐쇄 연구기지',palette:MAP_PALETTES.research,",
"  id:'research',name:'오로라 폐쇄 연구기지',trait:'정전 연구기지 · 시야 감소 / 고급 파츠 출현',visionMod:-1,waterPassable:false,waterSpeed:1,dynamicCoverBase:14,lootProfile:'research',palette:MAP_PALETTES.research,", 'research traits')
s = rep(s, "const BASE_MAP={id:'industrial',name:'칼리고 산업단지',palette:MAP_PALETTES.industrial,",
"const BASE_MAP={id:'industrial',name:'칼리고 산업단지',trait:'산업단지 · 엄폐물 밀집 / 근중거리 교전',visionMod:0,waterPassable:false,waterSpeed:1,dynamicCoverBase:36,lootProfile:'industrial',palette:MAP_PALETTES.industrial,", 'industrial traits')
s = rep(s, " for(const p of def.patrols)if(rectOverlap(c,safeRect(p.x,p.y,42)))return true;",
" for(const p of def.patrols)if(rectOverlap(c,safeRect(p.x,p.y,96)))return true;", 'patrol cover clearance')
s = rep(s, " const extraCount=28+Math.floor(rng()*8),shapes=[...movable];",
" const extraCount=(def.dynamicCoverBase??28)+Math.floor(rng()*7),shapes=[...movable];", 'map cover density')

s = rep(s,
"function weaponItem(type,quality=1,tier=1){const d=WEAPONS[type];return{kind:'weapon',id:uid('w'),type,name:d.name,damage:d.damage,ammo:d.mag,ammoTier:tier,value:Math.round(d.price*quality)}}\nfunction gearItem(key){const d=GEAR[key];return{id:uid('g'),key,...copy(d),value:d.price}}",
"function weaponItem(type,quality=1,tier=1){const d=WEAPONS[type],w={kind:'weapon',id:uid('w'),type,name:d.name,damage:d.damage,ammo:d.mag,ammoTier:tier,value:Math.round(d.price*quality),parts:{}};w.ammo=weaponMagCapacity(w);return w}\nfunction gearItem(key){const d=GEAR[key];return{id:uid('g'),key,...copy(d),value:d.price}}\nfunction partItem(key){const d=WEAPON_PARTS[key];return d?{id:uid('pt'),...copy(d),value:d.price}:null}", 'part item helper')

old_norm = "function normalizeItem(it){const x=copy(it);if(!x.id)x.id=uid('i');if(x.kind==='weapon'){const d=WEAPONS[x.type];x.name=x.name||d.name;x.ammo=x.ammo??d.mag;x.ammoTier=x.ammoTier||1;x.reserve=0;x.damage=x.damage??d.damage;x.value=x.value??d.price}else if(x.kind==='ammo'){x.caliber=x.caliber||WEAPONS[x.type]?.caliber||'9mm';x.tier=Math.max(1,Math.min(5,Number(x.tier)||1));x.qty=Math.max(0,Number(x.qty)||0);x.name=x.name||`${AMMO_CALIBERS[x.caliber]?.name||x.caliber} T${x.tier} 탄약`;x.value=x.value??Math.round(x.qty*(AMMO_TIERS[x.tier]?.unitPrice||3))}return x}"
new_norm = "function normalizeItem(it){const x=copy(it);if(!x.id)x.id=uid('i');if(x.kind==='weapon'){const d=WEAPONS[x.type];x.name=x.name||d.name;x.parts=x.parts&&typeof x.parts==='object'?x.parts:{};for(const [slot,part] of Object.entries(x.parts)){const pd=part?.key?WEAPON_PARTS[part.key]:null;if(!pd||!weaponAcceptsPart(x,pd))delete x.parts[slot];else x.parts[slot]={...copy(pd),...part,kind:'part',slot:pd.slot,value:part.value??pd.price}}x.ammo=x.ammo??weaponMagCapacity(x);x.ammoTier=x.ammoTier||1;x.reserve=0;x.damage=x.damage??d.damage;x.value=x.value??d.price}else if(x.kind==='ammo'){x.caliber=x.caliber||WEAPONS[x.type]?.caliber||'9mm';x.tier=Math.max(1,Math.min(5,Number(x.tier)||1));x.qty=Math.max(0,Number(x.qty)||0);x.name=x.name||`${AMMO_CALIBERS[x.caliber]?.name||x.caliber} T${x.tier} 탄약`;x.value=x.value??Math.round(x.qty*(AMMO_TIERS[x.tier]?.unitPrice||3))}else if(x.kind==='part'){const d=WEAPON_PARTS[x.key];if(d){Object.assign(x,copy(d),x);x.value=x.value??d.price}}return x}"
s = rep(s, old_norm, new_norm, 'normalize parts')

old_roll = "function rollCrate(i){const out=[];const names=['암호화 SSD','군용 무전기','광학 부품','공구 세트','의약품 박스','배터리 팩','제어 모듈'],cals=['9mm','5.56','7.62','12g'];out.push(valuable(names[i%names.length],260+Math.floor(Math.random()*650)));if(Math.random()<.72){const caliber=cals[i%cals.length],tier=Math.min(5,1+Math.floor(Math.pow(Math.random(),1.7)*5)),pack=AMMO_CALIBERS[caliber].pack;out.push(ammoItem(caliber,Math.max(6,Math.round(pack*(.55+Math.random()*.7))),tier))}if(Math.random()<.38)out.push(gearItem('med'));if(Math.random()<.24)out.push(gearItem('grenade'));if(Math.random()<.12)out.push(weaponItem(['smg','ar','shotgun','dmr'][i%4],1+.04*Math.random(),1+Math.floor(Math.random()*2)));return out}"
new_roll = "function rollCrate(i,def={}){const out=[];const names=def.lootProfile==='harbor'?['밀수 전자부품','항만 송수신기','선박 제어모듈','봉인 화물','냉동 의약품']:def.lootProfile==='research'?['실험 데이터 SSD','정밀 광학 모듈','연구 샘플','서버 제어보드','보안 키카드']:['암호화 SSD','군용 무전기','광학 부품','공구 세트','의약품 박스','배터리 팩','제어 모듈'],cals=['9mm','5.56','7.62','12g'];const valueMult=def.lootProfile==='harbor'?1.15:def.lootProfile==='research'?1.08:1;out.push(valuable(names[i%names.length],Math.round((260+Math.floor(Math.random()*650))*valueMult)));if(Math.random()<.72){const caliber=cals[i%cals.length],bonus=def.lootProfile==='research'&&Math.random()<.55?1:0,tier=Math.min(5,1+bonus+Math.floor(Math.pow(Math.random(),1.7)*5)),pack=AMMO_CALIBERS[caliber].pack;out.push(ammoItem(caliber,Math.max(6,Math.round(pack*(.55+Math.random()*.7))),tier))}if(Math.random()<.38)out.push(gearItem('med'));if(Math.random()<.24)out.push(gearItem('grenade'));if(Math.random()<(def.lootProfile==='research'?.36:def.lootProfile==='harbor'?.22:.16)){const keys=Object.keys(WEAPON_PARTS),pt=partItem(keys[(i+Math.floor(Math.random()*keys.length))%keys.length]);if(pt)out.push(pt)}if(Math.random()<.12)out.push(weaponItem(['smg','ar','shotgun','dmr'][i%4],1+.04*Math.random(),1+Math.floor(Math.random()*2)));return out}"
s = rep(s, old_roll, new_roll, 'crate map loot')

old_collision = "function pointHitsBlocker(w,x,y){for(const o of w.obstacles)if(x>o.x&&x<o.x+o.w&&y>o.y&&y<o.y+o.h)return true;for(const d of w.doors)if(!d.open&&x>d.x&&x<d.x+d.w&&y>d.y&&y<d.y+d.h)return true;return false}\nfunction blocked(w,x,y,r){if(x-r<0||y-r<0||x+r>WORLD_W||y+r>WORLD_H)return true;for(const o of w.obstacles)if(circleRect(x,y,r,o))return true;for(const d of w.doors)if(!d.open&&circleRect(x,y,r,d))return true;return false}\nfunction doorOccupied(w,d){for(const a of w.actors){if(!a.dead&&circleRect(a.x,a.y,(a.r||13)+5,d))return true}return false}\nfunction moveEntity(w,e,dx,dy){let moved=false;const nx=e.x+dx;if(!blocked(w,nx,e.y,e.r)){e.x=nx;moved=true}const ny=e.y+dy;if(!blocked(w,e.x,ny,e.r)){e.y=ny;moved=true}if(moved&&e.kind&&e.kind!=='player'){e.stepDist=(e.stepDist||0)+Math.hypot(dx,dy);if(e.stepDist>=58){e.stepDist=0;addSound(w,e.x,e.y,e.kind==='pmc'?190:155,'footstep',e.id)}}return moved}"
new_collision = "function solidObstacle(w,o){return !(o.kind==='water'&&w?.map?.waterPassable)}\nfunction pointInWater(w,x,y){return !!w?.map?.waterPassable&&w.obstacles.some(o=>o.kind==='water'&&x>o.x&&x<o.x+o.w&&y>o.y&&y<o.y+o.h)}\nfunction pointHitsBlocker(w,x,y){for(const o of w.obstacles)if(solidObstacle(w,o)&&x>o.x&&x<o.x+o.w&&y>o.y&&y<o.y+o.h)return true;for(const d of w.doors)if(!d.open&&x>d.x&&x<d.x+d.w&&y>d.y&&y<d.y+d.h)return true;return false}\nfunction blocked(w,x,y,r){if(x-r<0||y-r<0||x+r>WORLD_W||y+r>WORLD_H)return true;for(const o of w.obstacles)if(solidObstacle(w,o)&&circleRect(x,y,r,o))return true;for(const d of w.doors)if(!d.open&&circleRect(x,y,r,d))return true;return false}\nfunction nearestFreePoint(w,x,y,r,maxRadius=220){if(!blocked(w,x,y,r))return{x,y};for(let rad=18;rad<=maxRadius;rad+=18){const steps=Math.max(12,Math.ceil(rad/8));for(let i=0;i<steps;i++){const a=i/steps*Math.PI*2,nx=clamp(x+Math.cos(a)*rad,r+2,WORLD_W-r-2),ny=clamp(y+Math.sin(a)*rad,r+2,WORLD_H-r-2);if(!blocked(w,nx,ny,r))return{x:nx,y:ny}}}return null}\nfunction ensureActorFree(w,a){if(!a||a.dead||!blocked(w,a.x,a.y,a.r))return true;const q=nearestFreePoint(w,a.x,a.y,a.r,260);if(!q)return false;a.x=q.x;a.y=q.y;a.cover=null;a.lastKnown=null;a.heard=null;return true}\nfunction doorOccupied(w,d){for(const a of w.actors){if(!a.dead&&circleRect(a.x,a.y,(a.r||13)+5,d))return true}return false}\nfunction moveEntity(w,e,dx,dy){let moved=false;const terrain=pointInWater(w,e.x,e.y)?(w.map.waterSpeed||.62):1;dx*=terrain;dy*=terrain;const nx=e.x+dx;if(!blocked(w,nx,e.y,e.r)){e.x=nx;moved=true}const ny=e.y+dy;if(!blocked(w,e.x,ny,e.r)){e.y=ny;moved=true}if(moved&&e.kind&&e.kind!=='player'){e.stepDist=(e.stepDist||0)+Math.hypot(dx,dy);if(e.stepDist>=58){e.stepDist=0;const wet=pointInWater(w,e.x,e.y),base=e.kind==='pmc'?190:155;addSound(w,e.x,e.y,base*(wet?1.45:1),'footstep',e.id)}}return moved}"
s = rep(s, old_collision, new_collision, 'water and unstick collision')

s = rep(s, "grenadeCd:5+Math.random()*6,sleepAcc:0,interactLatch:false,visionLevel:load.visionLevel||3};",
"grenadeCd:5+Math.random()*6,sleepAcc:0,interactLatch:false,visionLevel:load.visionLevel||3,recoil:0};", 'actor recoil')

old_spawn = "function spawnFillerAI(w,index=0){\n const patrols=w.patrols||PATROLS,pos=patrols[(index+(w.aiSpawnSeq||0))%patrols.length];w.aiSpawnSeq=(w.aiSpawnSeq||0)+1;\n const pmc=(w.aiSpawnSeq%4===0),kind=pmc?'pmc':'scav',guns=pmc?['ar','dmr','smg']:['smg','shotgun','pistol','ar'];\n const gunType=guns[w.aiSpawnSeq%guns.length],tier=pmc?2:1,primary=weaponItem(gunType,pmc?1.02:.92,tier),inventory=[ammoItem(WEAPONS[gunType].caliber,AMMO_CALIBERS[WEAPONS[gunType].caliber].pack,tier)];if(Math.random()<.38)inventory.push(gearItem('med'));if(pmc&&Math.random()<.45)inventory.push(gearItem('grenade'));\n const a=makeActor(kind,pos.x+(Math.random()-.5)*80,pos.y+(Math.random()-.5)*80,pmc?`filler-pmc-${w.aiSpawnSeq}`:`filler-scav-${w.aiSpawnSeq}`,{name:pmc?`RAIDER-${60+w.aiSpawnSeq}`:`SCAV-${60+w.aiSpawnSeq}`,primary,inventory,patrols});a.filler=true;w.actors.push(a);return a\n}"
new_spawn = "function spawnFillerAI(w,index=0){\n const patrols=w.patrols||PATROLS,pos=patrols[(index+(w.aiSpawnSeq||0))%patrols.length];w.aiSpawnSeq=(w.aiSpawnSeq||0)+1;\n const pmc=(w.aiSpawnSeq%4===0),kind=pmc?'pmc':'scav',guns=pmc?['ar','dmr','smg']:['smg','shotgun','pistol','ar'];\n const gunType=guns[w.aiSpawnSeq%guns.length],tier=pmc?2:1,primary=weaponItem(gunType,pmc?1.02:.92,tier),inventory=[ammoItem(WEAPONS[gunType].caliber,AMMO_CALIBERS[WEAPONS[gunType].caliber].pack,tier)];if(pmc&&Math.random()<.42){const candidates=Object.keys(WEAPON_PARTS).filter(k=>weaponAcceptsPart(primary,WEAPON_PARTS[k]));if(candidates.length){const pt=partItem(candidates[Math.floor(Math.random()*candidates.length)]);primary.parts[pt.slot]=pt}}if(Math.random()<.38)inventory.push(gearItem('med'));if(pmc&&Math.random()<.45)inventory.push(gearItem('grenade'));\n let q=null;for(let tries=0;tries<18&&!q;tries++){const x=pos.x+(Math.random()-.5)*110,y=pos.y+(Math.random()-.5)*110;if(!blocked(w,x,y,13))q={x,y}}q=q||nearestFreePoint(w,pos.x,pos.y,13,280)||{x:pos.x,y:pos.y};\n const a=makeActor(kind,q.x,q.y,pmc?`filler-pmc-${w.aiSpawnSeq}`:`filler-scav-${w.aiSpawnSeq}`,{name:pmc?`RAIDER-${60+w.aiSpawnSeq}`:`SCAV-${60+w.aiSpawnSeq}`,primary,inventory,patrols});a.filler=true;w.actors.push(a);ensureActorFree(w,a);return a\n}"
s = rep(s, old_spawn, new_spawn, 'safe AI spawn')

old_world = " const players=config.players||[{}],def=selectedMap(config.mapIndex||0),layout=buildRaidObstacles(def,config.coverSeed),map={id:def.id,name:def.name,palette:copy(def.palette),roads:copy(def.roads),layoutSeed:layout.seed,dynamicCoverCount:layout.dynamicCount};"
new_world = " const players=config.players||[{}],def=selectedMap(config.mapIndex||0),layout=buildRaidObstacles(def,config.coverSeed),map={id:def.id,name:def.name,trait:def.trait||'',visionMod:def.visionMod||0,waterPassable:!!def.waterPassable,waterSpeed:def.waterSpeed||1,lootProfile:def.lootProfile||'industrial',palette:copy(def.palette),roads:copy(def.roads),layoutSeed:layout.seed,dynamicCoverCount:layout.dynamicCount};"
s = rep(s, old_world, new_world, 'world map traits')
s = rep(s, " def.crates.forEach((q,i)=>w.crates.push({id:`crate-${i}`,kind:'crate',x:q.x,y:q.y,r:19,opened:false,items:rollCrate(i)}));return w",
" def.crates.forEach((q,i)=>w.crates.push({id:`crate-${i}`,kind:'crate',x:q.x,y:q.y,r:19,opened:false,items:rollCrate(i,def)}));return w", 'world map loot')

# Restore a disconnected player from a recent client snapshot after a Vercel runtime/deployment replacement.
s = rep(s, "export function removeHumanPlayer(w,id,{drop=true}={}){",
"export function restoreHumanPlayer(w,state={}){const gear=state.gear||{},id=addHumanPlayer(w,{name:state.name||'PLAYER',equipment:{primary:gear.primary||null,secondary:gear.secondary||null,armor:gear.armor||null,helmet:gear.helmet||null,backpack:gear.backpack||null},inventory:state.inventory||[],visionLevel:state.baseVisionLevel||state.visionLevel||3}),a=getActor(w,id);if(!a)return id;const q=nearestFreePoint(w,Number(state.x)||a.x,Number(state.y)||a.y,a.r,300);if(q){a.x=q.x;a.y=q.y}a.hp=clamp(Number(state.hp)||a.hp,1,a.maxHp);a.kills=Math.max(0,Number(state.kills)||0);a.weaponSlot=state.weaponSlot==='secondary'&&a.gear.secondary?'secondary':'primary';a.recoil=Math.max(0,Number(state.recoil)||0);return id}\nexport function removeHumanPlayer(w,id,{drop=true}={}){", 'restore human')

# effective weapon mechanics
s = rep(s, "function ammoReserve(a,gun){if(!gun)return 0;const cal=WEAPONS[gun.type]?.caliber;return a.inventory.filter(i=>i.kind==='ammo'&&i.caliber===cal).reduce((n,i)=>n+(i.qty||0),0)}",
"function ammoReserve(a,gun){if(!gun)return 0;const cal=WEAPONS[gun.type]?.caliber;return a.inventory.filter(i=>i.kind==='ammo'&&i.caliber===cal).reduce((n,i)=>n+(i.qty||0),0)}\nfunction effectiveVisionLevel(w,a){const gun=currentWeapon(a),parts=weaponPartEffects(gun);return clamp((a.visionLevel||3)+(w.map?.visionMod||0)+(parts.visionBonus||0),1,10)}", 'effective vision')
s = rep(s, "function startReload(a){const gun=currentWeapon(a);if(!gun)return;const d=WEAPONS[gun.type],tier=reloadTierFor(a,gun);if(a.reload>0||gun.ammo>=d.mag||!tier)return;a.reload=d.reload;a.reloadTier=tier}",
"function startReload(a){const gun=currentWeapon(a);if(!gun)return;const d=WEAPONS[gun.type],tier=reloadTierFor(a,gun),cap=weaponMagCapacity(gun);if(a.reload>0||gun.ammo>=cap||!tier)return;a.reload=d.reload;a.reloadTier=tier}", 'reload cap')
s = rep(s, "function finishReload(a){const gun=currentWeapon(a);if(!gun){a.reload=0;return}const d=WEAPONS[gun.type],need=d.mag-gun.ammo;",
"function finishReload(a){const gun=currentWeapon(a);if(!gun){a.reload=0;return}const d=WEAPONS[gun.type],need=Math.max(0,weaponMagCapacity(gun)-gun.ammo);", 'finish reload cap')
old_shoot = "function shoot(w,a,aimX,aimY,ai=false){const gun=currentWeapon(a);if(!gun)return;const d=WEAPONS[gun.type];if(a.reload>0||a.fireCd>0||a.flinch>0)return;if(gun.ammo<=0){startReload(a);return}gun.ammo--;a.fireCd=d.rate;const base=Math.atan2(aimY,aimX),pellets=d.pellets||1,tier=gun.ammoTier||1,mult=AMMO_TIERS[tier]?.damageMult||1,shotDamage=(gun.damage||d.damage)*mult;for(let i=0;i<pellets;i++){const spread=d.spread*(ai?1.35:1),ang=base+(Math.random()-.5)*spread*2;w.bullets.push({id:uid('b'),owner:a.id,x:a.x+Math.cos(ang)*21,y:a.y+Math.sin(ang)*21,vx:Math.cos(ang)*d.speed,vy:Math.sin(ang)*d.speed,damage:shotDamage,life:d.range/d.speed,headChance:ai?.10:.18,ammoTier:tier})}if(w.bullets.length>360)w.bullets.splice(0,w.bullets.length-360);addSound(w,a.x,a.y,d.sound,'gunshot',a.id);emit(w,'shot',{actor:a.id,x:a.x,y:a.y,weapon:gun.type,ammoTier:tier,recoil:d.recoil,angle:base,ownerKind:a.kind})}"
new_shoot = "function shoot(w,a,aimX,aimY,ai=false){const gun=currentWeapon(a);if(!gun)return;const d=WEAPONS[gun.type],parts=weaponPartEffects(gun);if(a.reload>0||a.fireCd>0||a.flinch>0)return;if(gun.ammo<=0){startReload(a);return}gun.ammo--;a.fireCd=d.rate;const base=Math.atan2(aimY,aimX),pellets=d.pellets||1,tier=gun.ammoTier||1,mult=AMMO_TIERS[tier]?.damageMult||1,shotDamage=(gun.damage||d.damage)*mult,bloom=Math.min(.12,a.recoil||0),spread=(d.spread+bloom)*parts.spreadMult*(ai?1.28:1),kick=d.recoil*parts.recoilMult;for(let i=0;i<pellets;i++){const ang=base+(Math.random()-.5)*spread*2;w.bullets.push({id:uid('b'),owner:a.id,x:a.x+Math.cos(ang)*21,y:a.y+Math.sin(ang)*21,vx:Math.cos(ang)*d.speed,vy:Math.sin(ang)*d.speed,damage:shotDamage,life:d.range/d.speed,headChance:ai?.10:.18,ammoTier:tier})}a.recoil=Math.min(.115,(a.recoil||0)+kick*.0075);if(w.bullets.length>360)w.bullets.splice(0,w.bullets.length-360);addSound(w,a.x,a.y,d.sound,'gunshot',a.id);emit(w,'shot',{actor:a.id,x:a.x,y:a.y,weapon:gun.type,ammoTier:tier,recoil:kick,spread,angle:base,ownerKind:a.kind})}"
s = rep(s, old_shoot, new_shoot, 'recoil and spread')

old_player = "function movePlayer(w,p,dt){const inp=w.inputs[p.id]||emptyInput();updateHealing(w,p,dt);const healing=p.healTimer>0,v=norm(inp.moveX,inp.moveY);if(inp.moveX||inp.moveY){const sp=p.moveSpeed*(inp.sprint&&!healing?1.48:1)*(healing?0.55:1);moveEntity(w,p,v.x*sp*dt,v.y*sp*dt);p.stepCd-=dt;if(p.stepCd<=0){p.stepCd=(inp.sprint&&!healing)?0.36:0.58;addSound(w,p.x,p.y,inp.sprint&&!healing?380:135,'footstep',p.id)}}p.angle=Math.atan2(inp.aimY,inp.aimX);p.fireCd=Math.max(0,p.fireCd-dt);p.flinch=Math.max(0,p.flinch-dt);"
new_player = "function movePlayer(w,p,dt){const inp=w.inputs[p.id]||emptyInput();updateHealing(w,p,dt);p.recoil=Math.max(0,(p.recoil||0)-dt*.050);const healing=p.healTimer>0,v=norm(inp.moveX,inp.moveY);if(inp.moveX||inp.moveY){const sp=p.moveSpeed*(inp.sprint&&!healing?1.48:1)*(healing?0.55:1);moveEntity(w,p,v.x*sp*dt,v.y*sp*dt);p.stepCd-=dt;if(p.stepCd<=0){p.stepCd=(inp.sprint&&!healing)?0.36:0.58;const wet=pointInWater(w,p.x,p.y);addSound(w,p.x,p.y,(inp.sprint&&!healing?380:135)*(wet?1.55:1),'footstep',p.id)}}p.angle=Math.atan2(inp.aimY,inp.aimX);p.fireCd=Math.max(0,p.fireCd-dt);p.flinch=Math.max(0,p.flinch-dt);"
s = rep(s, old_player, new_player, 'player recoil decay and water sound')

s = rep(s, "function aiStep(w,a,dt){if(a.dead)return;a.fireCd=Math.max(0,a.fireCd-dt);",
"function aiStep(w,a,dt){if(a.dead)return;ensureActorFree(w,a);a.recoil=Math.max(0,(a.recoil||0)-dt*.060);a.fireCd=Math.max(0,a.fireCd-dt);", 'AI unstick recoil')
s = rep(s, "a.patrol={...PATROLS[Math.floor(Math.random()*PATROLS.length)]}",
"a.patrol={...(w.patrols||PATROLS)[Math.floor(Math.random()*(w.patrols||PATROLS).length)]}", 'map patrol reset')

old_snap = "export function buildSnapshot(w,viewerId){const p=getPlayer(w,viewerId);if(!p)return null;const pm=movementState(p);const visible=w.actors.filter(a=>a.id===viewerId||(!a.dead&&canSee(w,p,a,p.visionLevel))).map(actorPublic);const openId=w.openContainers[viewerId],oc=getContainer(w,openId);const interaction=w.interactions[viewerId]?copy(w.interactions[viewerId]):null;const gear={};for(const k of ['primary','secondary','armor','helmet','backpack'])gear[k]=publicItem(p.gear[k]);const gun=currentWeapon(p);return{time:w.time,timeLeft:w.timeLeft,map:copy(w.map),worldW:WORLD_W,worldH:WORLD_H,obstacles:w.obstacles,zones:w.zones,extracts:w.extracts,crates:w.crates.filter(c=>canSee(w,p,c,p.visionLevel)).map(c=>({id:c.id,x:c.x,y:c.y,opened:c.opened,empty:c.items.length===0})),corpses:w.corpses.filter(c=>canSee(w,p,c,p.visionLevel)).map(c=>({id:c.id,x:c.x,y:c.y,ownerName:c.ownerName,empty:c.items.length===0})),doors:w.doors.filter(d=>inVisionArc(p,{x:d.x+d.w/2,y:d.y+d.h/2},p.visionLevel)).map(d=>({id:d.id,name:d.name,x:d.x,y:d.y,w:d.w,h:d.h,open:d.open})),actors:visible,bullets:w.bullets.filter(b=>distXY(p.x,p.y,b.x,b.y)<1100).map(b=>({x:b.x,y:b.y,vx:b.vx,vy:b.vy,owner:b.owner})),grenades:w.grenades.filter(g=>distXY(p.x,p.y,g.x,g.y)<1100).map(g=>({x:g.x,y:g.y,fuse:g.fuse})),playerId:viewerId,aliveAI:w.actors.filter(a=>a.kind!=='player'&&!a.dead).length,player:{id:p.id,x:p.x,y:p.y,hp:p.hp,maxHp:p.maxHp,angle:p.angle,kills:p.kills,visionLevel:p.visionLevel,weaponSlot:p.weaponSlot,weapon:publicItem(gun),ammoReserve:gun?ammoReserve(p,gun):0,gear,inventory:p.inventory.map(publicItem),bagCapacity:bagCapacity(p),armor:p.gear.armor?.armor||0,maxArmor:p.gear.armor?.maxArmor||p.gear.armor?.armor||0,reload:p.reload,healTimer:p.healTimer||0,healDuration:p.healDuration||0,moving:pm.moving,sprinting:pm.sprinting,moveAngle:pm.moveAngle},openContainer:oc?{id:oc.id,kind:oc.kind,ownerName:oc.ownerName,items:oc.items.map(publicItem)}:null,interaction,result:w.results[viewerId]?copy(w.results[viewerId]):null};}"
new_snap = "export function buildSnapshot(w,viewerId){const p=getPlayer(w,viewerId);if(!p)return null;const pm=movementState(p),vision=effectiveVisionLevel(w,p);const visible=w.actors.filter(a=>a.id===viewerId||(!a.dead&&canSee(w,p,a,vision))).map(actorPublic);const openId=w.openContainers[viewerId],oc=getContainer(w,openId);const interaction=w.interactions[viewerId]?copy(w.interactions[viewerId]):null;const gear={};for(const k of ['primary','secondary','armor','helmet','backpack'])gear[k]=publicItem(p.gear[k]);const gun=currentWeapon(p),parts=weaponPartEffects(gun);return{time:w.time,timeLeft:w.timeLeft,map:copy(w.map),worldW:WORLD_W,worldH:WORLD_H,obstacles:w.obstacles,zones:w.zones,extracts:w.extracts,crates:w.crates.filter(c=>canSee(w,p,c,vision)).map(c=>({id:c.id,x:c.x,y:c.y,opened:c.opened,empty:c.items.length===0})),corpses:w.corpses.filter(c=>canSee(w,p,c,vision)).map(c=>({id:c.id,x:c.x,y:c.y,ownerName:c.ownerName,empty:c.items.length===0})),doors:w.doors.filter(d=>inVisionArc(p,{x:d.x+d.w/2,y:d.y+d.h/2},vision)).map(d=>({id:d.id,name:d.name,x:d.x,y:d.y,w:d.w,h:d.h,open:d.open})),actors:visible,bullets:w.bullets.filter(b=>distXY(p.x,p.y,b.x,b.y)<1250).map(b=>({x:b.x,y:b.y,vx:b.vx,vy:b.vy,owner:b.owner})),grenades:w.grenades.filter(g=>distXY(p.x,p.y,g.x,g.y)<1250).map(g=>({x:g.x,y:g.y,fuse:g.fuse})),playerId:viewerId,aliveAI:w.actors.filter(a=>a.kind!=='player'&&!a.dead).length,player:{id:p.id,name:p.name,x:p.x,y:p.y,hp:p.hp,maxHp:p.maxHp,angle:p.angle,kills:p.kills,baseVisionLevel:p.visionLevel,visionLevel:vision,scopeLead:parts.viewLead||0,recoil:p.recoil||0,weaponSlot:p.weaponSlot,weapon:publicItem(gun),magCapacity:gun?weaponMagCapacity(gun):0,ammoReserve:gun?ammoReserve(p,gun):0,gear,inventory:p.inventory.map(publicItem),bagCapacity:bagCapacity(p),armor:p.gear.armor?.armor||0,maxArmor:p.gear.armor?.maxArmor||p.gear.armor?.armor||0,reload:p.reload,healTimer:p.healTimer||0,healDuration:p.healDuration||0,moving:pm.moving,sprinting:pm.sprinting,moveAngle:pm.moveAngle},openContainer:oc?{id:oc.id,kind:oc.kind,ownerName:oc.ownerName,items:oc.items.map(publicItem)}:null,interaction,result:w.results[viewerId]?copy(w.results[viewerId]):null};}"
s = rep(s, old_snap, new_snap, 'snapshot parts vision recoil')
p.write_text(s, encoding='utf-8')

# ---------- client transport: 150 sec reconnect + snapshot recovery ----------
Path('src/net.js').write_text(r'''import {createWorld,stepWorld,setPlayerInput,applyAction,buildSnapshot,drainEvents} from './sim.js';

const RESUME_KEY='deadDropRaidResumeV1';
const DEFAULT_RECONNECT_GRACE_MS=150_000;

function loadResume(){
  try{
    const raw=localStorage.getItem(RESUME_KEY);if(!raw)return null;
    const data=JSON.parse(raw);if(!data?.token)return null;
    if(data.endsAt&&Date.now()>data.endsAt+DEFAULT_RECONNECT_GRACE_MS){localStorage.removeItem(RESUME_KEY);return null}
    return data;
  }catch{return null}
}
function saveResume(data){try{localStorage.setItem(RESUME_KEY,JSON.stringify(data))}catch{}}
function clearResume(){try{localStorage.removeItem(RESUME_KEY)}catch{}}
function recoveryFromSnapshot(s){const p=s?.player;if(!p)return null;return{name:p.name,x:p.x,y:p.y,hp:p.hp,maxHp:p.maxHp,kills:p.kills,baseVisionLevel:p.baseVisionLevel||p.visionLevel,weaponSlot:p.weaponSlot,recoil:p.recoil||0,gear:p.gear,inventory:p.inventory}}

class Emitter{constructor(){this.handlers=new Map()}on(name,fn){if(!this.handlers.has(name))this.handlers.set(name,new Set());this.handlers.get(name).add(fn);return()=>this.handlers.get(name)?.delete(fn)}emit(name,data){for(const fn of this.handlers.get(name)||[])fn(data)}}

export class LocalSession extends Emitter{
 constructor(config={}){super();const now=Date.now(),cycle=Math.floor(now/(10*60*1000));this.closed=false;this.world=createWorld({players:[config],mapIndex:((cycle%3)+3)%3,coverSeed:now});this.playerId=this.world.humanIds[0];this.acc=0;this.last=performance.now();this.timer=setInterval(()=>this.loop(),16);this.snapshotTimer=setInterval(()=>this.pushSnapshot(),50);this.pushSnapshot()}
 loop(){if(this.closed)return;const now=performance.now(),frame=Math.min(.08,(now-this.last)/1000);this.last=now;this.acc+=frame;const FIXED=1/30;let guard=0;while(this.acc>=FIXED&&guard++<4){stepWorld(this.world,FIXED);this.acc-=FIXED;for(const e of drainEvents(this.world)){if(!e.recipient||e.recipient===this.playerId)this.emit('event',e)}}}
 pushSnapshot(){if(!this.closed)this.emit('snapshot',buildSnapshot(this.world,this.playerId))}
 sendInput(input){if(!this.closed)setPlayerInput(this.world,this.playerId,input)}sendAction(action){if(!this.closed)applyAction(this.world,this.playerId,action)}close(){if(this.closed)return;this.closed=true;clearInterval(this.timer);clearInterval(this.snapshotTimer)}
}

export class WebSocketSession extends Emitter{
 constructor(url){super();const saved=loadResume();this.url=url;this.ws=null;this.manual=false;this.joined=false;this.pendingJoin=null;this.lastSnapshot=null;this.reconnectTimer=null;this.disconnectTimer=null;this.resumeToken=saved?.token||null;this.resumeInfo=saved||null;this.reconnectGraceMs=Number(saved?.reconnectGraceMs)||DEFAULT_RECONNECT_GRACE_MS;this.connect()}
 get connected(){return this.ws?.readyState===1}
 socketUrl(){if(!this.resumeToken||!this.resumeInfo?.roomKey)return this.url;try{const u=new URL(this.url,location.href);u.searchParams.set('roomKey',String(this.resumeInfo.roomKey));return u.toString()}catch{return this.url}}
 connect(){if(this.manual)return;this.ws=new WebSocket(this.socketUrl());this.ws.addEventListener('open',()=>{this.emit('connection',{connected:true});this.ws.send(JSON.stringify({type:'watch'}));if(this.resumeToken)this._sendResume();else if(this.pendingJoin)this._sendJoin()});this.ws.addEventListener('message',e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='status')this.emit('status',m.data);else if(m.type==='joined'){this.joined=true;clearTimeout(this.disconnectTimer);this.disconnectTimer=null;this.pendingJoin=null;if(m.data?.resumeToken){this.resumeToken=m.data.resumeToken;this.reconnectGraceMs=Number(m.data.reconnectGraceMs)||DEFAULT_RECONNECT_GRACE_MS;this.resumeInfo={...(this.resumeInfo||{}),token:this.resumeToken,roomId:m.data.roomId||null,roomKey:m.data.roomKey??this.resumeInfo?.roomKey??null,endsAt:m.data.endsAt||0,reconnectGraceMs:this.reconnectGraceMs,savedAt:Date.now()};saveResume(this.resumeInfo)}this.emit('joined',m.data)}else if(m.type==='resume_denied'){this.joined=false;this.pendingJoin=null;clearTimeout(this.disconnectTimer);this.disconnectTimer=null;this._clearResume();this.emit('resume_denied',m);this.emit('disconnect',{reason:m.reason||'재접속 제한 시간이 초과되었습니다.'})}else if(m.type==='join_denied'){this.pendingJoin=null;this.emit('join_denied',m)}else if(m.type==='snapshot'){this.lastSnapshot=m.full||!this.lastSnapshot?m.data:{...this.lastSnapshot,...m.data};if(this.resumeToken&&this.resumeInfo){this.resumeInfo.recovery=recoveryFromSnapshot(this.lastSnapshot);this.resumeInfo.roomKey=this.lastSnapshot?.room?.roomKey??this.resumeInfo.roomKey;this.resumeInfo.endsAt=this.lastSnapshot?.room?.endsAt??this.resumeInfo.endsAt;this.resumeInfo.savedAt=Date.now();saveResume(this.resumeInfo)}this.emit('snapshot',this.lastSnapshot)}else if(m.type==='event')this.emit('event',m.data);else if(m.type==='left'){this.joined=false;this.lastSnapshot=null;this._clearResume();this.emit('left')}});this.ws.addEventListener('close',()=>{const wasJoined=this.joined;this.joined=false;this.emit('connection',{connected:false});if(wasJoined&&this.resumeToken)this._armDisconnectTimeout();else if(wasJoined)this.emit('disconnect',{reason:'멀티 서버 연결 끊김'});if(!this.manual){clearTimeout(this.reconnectTimer);this.reconnectTimer=setTimeout(()=>this.connect(),1000)}});this.ws.addEventListener('error',()=>{})}
 _armDisconnectTimeout(){clearTimeout(this.disconnectTimer);this.disconnectTimer=setTimeout(()=>{if(this.joined)return;this.pendingJoin=null;this._clearResume();this.emit('disconnect',{reason:'재접속 제한 시간 2분 30초 초과'})},Math.max(1000,this.reconnectGraceMs+1500))}
 _sendJoin(){if(this.connected&&this.pendingJoin)this.ws.send(JSON.stringify({type:'join',data:this.pendingJoin}))}
 _sendResume(){if(this.connected&&this.resumeToken)this.ws.send(JSON.stringify({type:'resume',data:{token:this.resumeToken,roomKey:this.resumeInfo?.roomKey,recovery:this.resumeInfo?.recovery||null,savedAt:this.resumeInfo?.savedAt||0}}))}
 _clearResume(){this.resumeToken=null;this.resumeInfo=null;clearResume()}
 join(config){this.pendingJoin=config;if(this.connected){if(this.resumeToken)this._sendResume();else this._sendJoin()}}
 leave(){this.pendingJoin=null;clearTimeout(this.disconnectTimer);this.disconnectTimer=null;this._clearResume();if(this.connected)this.ws.send(JSON.stringify({type:'leave'}));this.joined=false;this.lastSnapshot=null}
 sendInput(input){if(this.connected&&this.joined)this.ws.send(JSON.stringify({type:'input',data:input}))}sendAction(action){if(this.connected&&this.joined)this.ws.send(JSON.stringify({type:'action',data:action}))}close(){this.manual=true;clearTimeout(this.reconnectTimer);clearTimeout(this.disconnectTimer);this.ws?.close()}
}
''', encoding='utf-8')

# ---------- Vercel realtime server ----------
Path('api/realtime.js').write_text(r'''import {experimental_upgradeWebSocket} from '@vercel/functions';
import {createWorld,stepWorld,setPlayerInput,applyAction,buildSnapshot,drainEvents,addHumanPlayer,restoreHumanPlayer,removeHumanPlayer,reconcileFillerAI} from '../src/sim.js';
import {emptyInput} from '../src/protocol.js';

const CYCLE_MS=10*60*1000,CAPACITY=8,ENTRY_LOCK_MS=60_000,FIXED=1/30,SNAPSHOT_MS=50,STATUS_MS=1000,RECONNECT_GRACE_MS=150_000;
const shared=globalThis.__DEAD_DROP_RT_V340__||(globalThis.__DEAD_DROP_RT_V340__={rooms:new Map(),sockets:new Set(),socketMeta:new WeakMap(),resumes:new Map(),timer:null,lastTick:Date.now(),lastStatus:0});
const sm=ws=>{let d=shared.socketMeta.get(ws);if(!d){d={roomKey:null,playerId:null,resumeToken:null,fullSent:false};shared.socketMeta.set(ws,d)}return d};
const safeSend=(ws,msg)=>{try{ws.send(JSON.stringify(msg))}catch{}};
const roomKey=(now=Date.now())=>Math.floor(now/CYCLE_MS),roomId=k=>`IND-${String(k).slice(-6)}`;
function createRoom(key){const start=key*CYCLE_MS,end=start+CYCLE_MS,mapIndex=((key%3)+3)%3,world=createWorld({players:[],aiCount:CAPACITY,mapIndex,coverSeed:key});world.timeLeft=Math.max(0,(end-Date.now())/1000);const r={key,id:roomId(key),start,end,world,clients:new Set(),byPlayer:new Map(),nextAiFill:start+60_000,lastSnapshot:0,ended:false};shared.rooms.set(key,r);return r}
function getRoom(key){return shared.rooms.get(key)||createRoom(key)}
function currentRoom(now=Date.now()){return getRoom(roomKey(now))}
function liveHumans(r){return r.world.actors.filter(a=>a.kind==='player'&&!a.dead&&!r.world.results[a.id]).length}
function liveAI(r){return r.world.actors.filter(a=>a.kind!=='player'&&!a.dead).length}
function statusFor(r,now=Date.now()){const humans=liveHumans(r),remainingMs=Math.max(0,r.end-now),entryClosed=remainingMs<=ENTRY_LOCK_MS;return{roomId:r.id,roomKey:r.key,humans,ai:liveAI(r),capacity:CAPACITY,endsAt:r.end,remainingMs,entryClosed,mapId:r.world.map?.id,mapName:r.world.map?.name,mapTrait:r.world.map?.trait||'',joinable:humans<CAPACITY&&!entryClosed}}
function statusData(now=Date.now()){return statusFor(currentRoom(now),now)}
function broadcastStatus(now=Date.now()){const data=statusData(now);for(const ws of shared.sockets)safeSend(ws,{type:'status',data})}
function removePlayerFromRoom(r,id,{drop=true}={}){if(!r||!id)return;const hadResult=!!r.world.results[id];removeHumanPlayer(r.world,id,{drop:drop&&!hadResult});r.byPlayer.delete(id);for(const [token,rec] of shared.resumes)if(rec.roomKey===r.key&&rec.playerId===id)shared.resumes.delete(token)}
function cleanupPlayer(ws,{drop=true}={}){const d=sm(ws),r=shared.rooms.get(d.roomKey),id=d.playerId;if(r&&id){removePlayerFromRoom(r,id,{drop});r.clients.delete(ws)}if(d.resumeToken)shared.resumes.delete(d.resumeToken);d.roomKey=null;d.playerId=null;d.resumeToken=null;d.fullSent=false}
function markDisconnected(ws){const d=sm(ws),r=shared.rooms.get(d.roomKey),id=d.playerId;if(!r||!id)return;setPlayerInput(r.world,id,emptyInput());r.clients.delete(ws);r.byPlayer.delete(id);const rec=d.resumeToken?shared.resumes.get(d.resumeToken):null;if(rec&&rec.playerId===id&&rec.roomKey===r.key){rec.expiresAt=Date.now()+RECONNECT_GRACE_MS;shared.resumes.set(d.resumeToken,rec)}else removePlayerFromRoom(r,id,{drop:true});d.roomKey=null;d.playerId=null;d.resumeToken=null;d.fullSent=false}
function attachSocketToPlayer(ws,r,id,token,resumed){const d=sm(ws);const old=r.byPlayer.get(id);if(old&&old!==ws){const od=sm(old);od.roomKey=null;od.playerId=null;od.resumeToken=null;od.fullSent=false;try{old.close()}catch{}}const nextToken=crypto.randomUUID();if(token)shared.resumes.delete(token);shared.resumes.set(nextToken,{roomKey:r.key,playerId:id,expiresAt:0});d.roomKey=r.key;d.playerId=id;d.resumeToken=nextToken;d.fullSent=false;r.byPlayer.set(id,ws);r.clients.add(ws);safeSend(ws,{type:'joined',data:{playerId:id,roomId:r.id,roomKey:r.key,endsAt:r.end,resumeToken:nextToken,reconnectGraceMs:RECONNECT_GRACE_MS,resumed}});const snap=buildSnapshot(r.world,id);if(snap){snap.room=statusFor(r);safeSend(ws,{type:'snapshot',full:true,data:snap});d.fullSent=true}}
function joinCurrent(ws,config={}){const d=sm(ws);if(d.playerId)return;const r=currentRoom(),humans=liveHumans(r),remainingMs=Math.max(0,r.end-Date.now());if(humans>=CAPACITY||remainingMs<=ENTRY_LOCK_MS)return safeSend(ws,{type:'join_denied',reason:humans>=CAPACITY?'현재 방이 가득 찼습니다.':'현재 RAID는 종료 1분 전이라 신규 참가가 마감되었습니다.'});reconcileFillerAI(r.world,Math.max(0,CAPACITY-(humans+1)),{onlyRemove:true});const id=addHumanPlayer(r.world,{...config,name:(config.name||'PLAYER').slice(0,18)});attachSocketToPlayer(ws,r,id,null,false)}
function resume(ws,data={}){const token=String(data.token||''),now=Date.now();let rec=shared.resumes.get(token);if(rec&&rec.expiresAt>0&&now>rec.expiresAt){const r=shared.rooms.get(rec.roomKey);if(r)removePlayerFromRoom(r,rec.playerId,{drop:true});shared.resumes.delete(token);rec=null}if(rec){const r=shared.rooms.get(rec.roomKey),actor=r?.world.actors.find(a=>a.id===rec.playerId);if(r&&actor)return attachSocketToPlayer(ws,r,rec.playerId,token,true);shared.resumes.delete(token)}
 const key=Number(data.roomKey),savedAt=Number(data.savedAt)||0,recovery=data.recovery,current=roomKey(now);if(!Number.isFinite(key)||key<current-1||key>current||!recovery||now-savedAt>RECONNECT_GRACE_MS+15_000)return safeSend(ws,{type:'resume_denied',reason:'복귀 가능한 RAID 세션이 없거나 재접속 시간이 초과되었습니다.'});const r=getRoom(key);if(now>r.end+RECONNECT_GRACE_MS)return safeSend(ws,{type:'resume_denied',reason:'해당 RAID가 이미 종료되었습니다.'});const humans=liveHumans(r);if(humans>=CAPACITY)return safeSend(ws,{type:'resume_denied',reason:'복구할 방의 플레이어 슬롯이 가득 찼습니다.'});reconcileFillerAI(r.world,Math.max(0,CAPACITY-(humans+1)),{onlyRemove:true});const id=restoreHumanPlayer(r.world,recovery);attachSocketToPlayer(ws,r,id,token,true)}
function handleMessage(ws,raw){let m;try{m=JSON.parse(raw.toString())}catch{return}if(m.type==='watch')return safeSend(ws,{type:'status',data:statusData()});if(m.type==='join')return joinCurrent(ws,m.data||{});if(m.type==='resume')return resume(ws,m.data||{});if(m.type==='leave'){cleanupPlayer(ws,{drop:true});return safeSend(ws,{type:'left'})}const d=sm(ws),r=shared.rooms.get(d.roomKey),id=d.playerId;if(!r||!id)return;if(m.type==='input')setPlayerInput(r.world,id,m.data||{});else if(m.type==='action')applyAction(r.world,id,m.data||{})}
function sendEvents(r){for(const e of drainEvents(r.world)){if(e.recipient){const ws=r.byPlayer.get(e.recipient);if(ws)safeSend(ws,{type:'event',data:e})}else for(const ws of r.clients)safeSend(ws,{type:'event',data:e})}}
function sendSnapshots(r,now){if(now-r.lastSnapshot<SNAPSHOT_MS)return;r.lastSnapshot=now;const st=statusFor(r,now);for(const [id,ws] of r.byPlayer){const snap=buildSnapshot(r.world,id);if(!snap)continue;snap.room=st;const d=sm(ws),full=!d.fullSent;if(!full){delete snap.obstacles;delete snap.zones;delete snap.extracts;delete snap.worldW;delete snap.worldH}safeSend(ws,{type:'snapshot',full,data:snap});d.fullSent=true}}
function cleanupExpiredResumes(now){for(const [token,rec] of [...shared.resumes]){if(!(rec.expiresAt>0)||now<rec.expiresAt)continue;const r=shared.rooms.get(rec.roomKey);if(r&&!r.byPlayer.has(rec.playerId))removePlayerFromRoom(r,rec.playerId,{drop:true});shared.resumes.delete(token)}}
function tick(){const now=Date.now(),elapsed=Math.min(.1,Math.max(0,(now-shared.lastTick)/1000));shared.lastTick=now;currentRoom(now);cleanupExpiredResumes(now);for(const [key,r] of shared.rooms){const remaining=Math.max(0,(r.end-now)/1000);r.world.timeLeft=remaining;if(remaining>0){r._acc=(r._acc||0)+elapsed;let guard=0;while(r._acc>=FIXED&&guard++<4){stepWorld(r.world,FIXED);r._acc-=FIXED;r.world.timeLeft=Math.max(0,(r.end-Date.now())/1000)}}else if(!r.ended){r.world.timeLeft=0;stepWorld(r.world,.001);r.ended=true}if(remaining>0&&now>=r.nextAiFill){reconcileFillerAI(r.world,Math.max(0,CAPACITY-liveHumans(r)));while(r.nextAiFill<=now)r.nextAiFill+=60_000}sendEvents(r);sendSnapshots(r,now);const hasResume=[...shared.resumes.values()].some(x=>x.roomKey===key);if(now>r.end+RECONNECT_GRACE_MS&&r.byPlayer.size===0&&!hasResume)shared.rooms.delete(key)}if(now-shared.lastStatus>=STATUS_MS){shared.lastStatus=now;broadcastStatus(now)}}
if(!shared.timer)shared.timer=setInterval(tick,16);
function upgrade(){return experimental_upgradeWebSocket(ws=>{sm(ws);shared.sockets.add(ws);safeSend(ws,{type:'hello',data:{protocol:2,serverTime:Date.now(),reconnectGraceMs:RECONNECT_GRACE_MS}});safeSend(ws,{type:'status',data:statusData()});ws.on('message',data=>handleMessage(ws,data));ws.on('close',()=>{markDisconnected(ws);shared.sockets.delete(ws)});ws.on('error',()=>{})},{maxPayload:256*1024})}
export async function GET(){return upgrade()}
export default {fetch(request){if(request.headers.get('upgrade')?.toLowerCase()==='websocket')return upgrade();return Response.json({ok:false,message:'WebSocket upgrade required',room:statusData()},{status:426})}};
''', encoding='utf-8')

# ---------- Cloudflare parity ----------
wp = Path('cloudflare/worker.js')
w = wp.read_text(encoding='utf-8')
w = w.replace('const RECONNECT_GRACE_MS = 30_000;', 'const RECONNECT_GRACE_MS = 150_000;')
w = rep(w, "    const now = Date.now();\n    const key = roomKey(now);\n    const id = env.RAID_ROOMS.idFromName(String(key));\n    const stub = env.RAID_ROOMS.get(id);\n    const url = new URL(request.url);",
"    const now = Date.now();\n    const currentKey = roomKey(now);\n    const url = new URL(request.url);\n    const requestedKey = Number(url.searchParams.get('roomKey'));\n    const wantsWs = request.headers.get('Upgrade')?.toLowerCase() === 'websocket';\n    const key = wantsWs && Number.isFinite(requestedKey) && requestedKey >= currentKey - 1 && requestedKey <= currentKey ? requestedKey : currentKey;\n    const id = env.RAID_ROOMS.idFromName(String(key));\n    const stub = env.RAID_ROOMS.get(id);", 'cloudflare old room route')
w = w.replace("roomId: roomId(this.key), endsAt: this.endsAt, resumeToken: nextToken, reconnectGraceMs: RECONNECT_GRACE_MS, resumed: true", "roomId: roomId(this.key), roomKey: this.key, endsAt: this.endsAt, resumeToken: nextToken, reconnectGraceMs: RECONNECT_GRACE_MS, resumed: true")
w = w.replace("roomId: roomId(this.key), endsAt: this.endsAt, resumeToken, reconnectGraceMs: RECONNECT_GRACE_MS, resumed: false", "roomId: roomId(this.key), roomKey: this.key, endsAt: this.endsAt, resumeToken, reconnectGraceMs: RECONNECT_GRACE_MS, resumed: false")
w = w.replace("reason: '재접속 제한 시간 30초를 초과했습니다.'", "reason: '재접속 제한 시간 2분 30초를 초과했습니다.'")
wp.write_text(w, encoding='utf-8')

# ---------- lobby/UI ----------
mp = Path('src/main.js')
m = mp.read_text(encoding='utf-8')
m = rep(m, "import {WEAPONS,GEAR,AMMO_TIERS,AMMO_CALIBERS,AMMO_STACK_MAX} from './sim.js';",
"import {WEAPONS,GEAR,WEAPON_PARTS,weaponAcceptsPart,weaponPartEffects,weaponMagCapacity,AMMO_TIERS,AMMO_CALIBERS,AMMO_STACK_MAX} from './sim.js';", 'main parts import')
m = rep(m, "const makeWeapon=type=>({id:id(),kind:'weapon',type,name:WEAPONS[type].name,ammo:0,ammoTier:1,reserve:0,damage:WEAPONS[type].damage,value:WEAPONS[type].price});",
"const makeWeapon=type=>({id:id(),kind:'weapon',type,name:WEAPONS[type].name,ammo:0,ammoTier:1,reserve:0,damage:WEAPONS[type].damage,value:WEAPONS[type].price,parts:{}});\nconst makePart=key=>({id:id(),...cp(WEAPON_PARTS[key]),value:WEAPON_PARTS[key].price});", 'main make parts')
m = rep(m, "migrateAmmoEconomy();\nmeta.inventory=compactMetaAmmo(meta.inventory);meta.stash=compactMetaAmmo(meta.stash);save();",
"migrateAmmoEconomy();\nfunction migrateWeaponParts(){const all=[meta.equipment?.primary,meta.equipment?.secondary,...(meta.inventory||[]),...(meta.stash||[])].filter(Boolean);for(const it of all)if(it.kind==='weapon'&&!it.parts)it.parts={};if(!meta.weaponPartsV1){meta.stash.push(makePart('optic_2x'),makePart('vertical_grip'));meta.weaponPartsV1=true}save()}\nmigrateWeaponParts();\nmeta.inventory=compactMetaAmmo(meta.inventory);meta.stash=compactMetaAmmo(meta.stash);save();", 'parts migration')

old_sell = "function sellPrice(it){if(!it||it.starterIssue||(it.value||0)<=0)return 0;const rate=it.kind==='valuable'?1:it.kind==='ammo'?.75:it.kind==='weapon'?.65:.7;return Math.max(1,Math.round((it.value||0)*rate*(.55+.45*conditionRatio(it))))}"
new_sell = "function sellPrice(it){if(!it||it.starterIssue||(it.value||0)<=0)return 0;const partValue=it.kind==='weapon'?Object.values(it.parts||{}).reduce((s,p)=>s+(p?.value||WEAPON_PARTS[p?.key]?.price||0),0):0,base=(it.value||0)+partValue,rate=it.kind==='valuable'?1:it.kind==='ammo'?.75:it.kind==='weapon'?.65:.7;return Math.max(1,Math.round(base*rate*(.55+.45*conditionRatio(it))))}"
m = rep(m, old_sell, new_sell, 'weapon part sell value')

old_meta = "function itemMeta(it){if(!it)return'';if(it.kind==='weapon'){const w=weaponSpec(it.type);return`${weaponDesc[it.type]} · ${AMMO_CALIBERS[WEAPONS[it.type].caliber]?.name||WEAPONS[it.type].caliber} · 기본 DMG ${w.damage} · ${w.rpm} RPM · 탄창 ${it.ammo??0}/${WEAPONS[it.type].mag} · 현재 T${it.ammoTier||1}`};if(it.kind==='ammo'){const t=AMMO_TIERS[it.tier||1];return`${AMMO_CALIBERS[it.caliber]?.name||it.caliber} · T${it.tier||1} · ${it.qty||0}/${AMMO_STACK_MAX}발 · 해당 탄 사용 시 무기 피해 ×${(t?.damageMult||1).toFixed(2)}`};if(it.kind==='armor')return`몸통 피격 피해 일부 흡수 · 방탄 ${Math.round(it.armor??it.maxArmor??0)}/${it.maxArmor||0} · 손상 시 로비에서 수리`;if(it.kind==='helmet')return`머리 피격 피해 일부 흡수 · 내구 ${Math.round(it.durability??it.maxDurability??0)}/${it.maxDurability||0} · 손상 시 로비에서 수리`;if(it.kind==='backpack')return`휴대 가능 가방 슬롯을 ${it.capacity||8}칸으로 확장`;if(it.kind==='med')return`H키 · 2초 사용 · HP +${it.heal} · 사용 중 사격 불가`;if(it.kind==='grenade')return`G키 · 폭발 피해 ${it.damage||92} · 반경 ${it.radius||165}`;if(it.kind==='valuable')return`탈출 후 판매하는 전리품 · 평가 ${money(it.value)}`;return`평가 가치 ${money(it.value)}`}"
new_meta = "function itemMeta(it){if(!it)return'';if(it.kind==='weapon'){const w=weaponSpec(it.type),fx=weaponPartEffects(it),parts=Object.values(it.parts||{}).map(p=>p.name||WEAPON_PARTS[p.key]?.name).filter(Boolean);return`${weaponDesc[it.type]} · ${AMMO_CALIBERS[WEAPONS[it.type].caliber]?.name||WEAPONS[it.type].caliber} · 기본 DMG ${w.damage} · ${w.rpm} RPM · 탄창 ${it.ammo??0}/${weaponMagCapacity(it)} · 반동 ×${fx.recoilMult.toFixed(2)} · 집탄 ×${fx.spreadMult.toFixed(2)} · 현재 T${it.ammoTier||1}${parts.length?` · 파츠 ${parts.join(' / ')}`:''}`};if(it.kind==='part'){const d=WEAPON_PARTS[it.key]||it,stats=[];if(d.visionBonus)stats.push(`시야 +${d.visionBonus}`);if(d.viewLead)stats.push(`전방 시야 +${d.viewLead}`);if(d.magMult&&d.magMult!==1)stats.push(`탄창 ×${d.magMult}`);if(d.magBonus)stats.push(`탄창 +${d.magBonus}`);if(d.spreadMult)stats.push(`탄퍼짐 ×${d.spreadMult}`);if(d.recoilMult)stats.push(`반동 ×${d.recoilMult}`);return`${d.slot==='optic'?'조준경':d.slot==='mag'?'탄창':'손잡이'} · ${stats.join(' · ')} · 호환 ${(d.compatible||[]).map(k=>WEAPONS[k]?.name||k).join(', ')}`};if(it.kind==='ammo'){const t=AMMO_TIERS[it.tier||1];return`${AMMO_CALIBERS[it.caliber]?.name||it.caliber} · T${it.tier||1} · ${it.qty||0}/${AMMO_STACK_MAX}발 · 해당 탄 사용 시 무기 피해 ×${(t?.damageMult||1).toFixed(2)}`};if(it.kind==='armor')return`몸통 피격 피해 일부 흡수 · 방탄 ${Math.round(it.armor??it.maxArmor??0)}/${it.maxArmor||0} · 손상 시 로비에서 수리`;if(it.kind==='helmet')return`머리 피격 피해 일부 흡수 · 내구 ${Math.round(it.durability??it.maxDurability??0)}/${it.maxDurability||0} · 손상 시 로비에서 수리`;if(it.kind==='backpack')return`휴대 가능 가방 슬롯을 ${it.capacity||8}칸으로 확장`;if(it.kind==='med')return`H키 · 2초 사용 · HP +${it.heal} · 사용 중 사격 불가`;if(it.kind==='grenade')return`G키 · 폭발 피해 ${it.damage||92} · 반경 ${it.radius||165}`;if(it.kind==='valuable')return`탈출 후 판매하는 전리품 · 평가 ${money(it.value)}`;return`평가 가치 ${money(it.value)}`}"
m = rep(m, old_meta, new_meta, 'main item meta')

m = rep(m, "function sellFromStash(i){const it=meta.stash[i],price=sellPrice(it);if(!it||price<=0)return;meta.money+=price;meta.stash.splice(i,1);save();renderLobby()}",
"function sellFromStash(i){const it=meta.stash[i],price=sellPrice(it);if(!it||price<=0)return;meta.money+=price;meta.stash.splice(i,1);save();renderLobby()}\nfunction attachPartFrom(source,index,targetSlot){const part=source[index],weapon=meta.equipment[targetSlot];if(!part||part.kind!=='part'||!weaponAcceptsPart(weapon,part))return;const slot=WEAPON_PARTS[part.key]?.slot||part.slot;source.splice(index,1);weapon.parts=weapon.parts||{};const old=weapon.parts[slot];weapon.parts[slot]=part;if(old)meta.stash.push(old);save();renderLobby()}\nfunction detachWeaponPart(targetSlot,partSlot){const weapon=meta.equipment[targetSlot],part=weapon?.parts?.[partSlot];if(!part)return;delete weapon.parts[partSlot];meta.stash.push(part);save();renderLobby()}\nfunction addPartAttachButtons(actions,it,source,index){if(it?.kind!=='part')return;for(const [slot,label] of [['primary','주무기'],['secondary','보조무기']]){const weapon=meta.equipment[slot];if(!weaponAcceptsPart(weapon,it))continue;const b=document.createElement('button');b.textContent=`${label} 장착`;b.onclick=()=>attachPartFrom(source,index,slot);actions.appendChild(b)}}\nfunction addPartDetachButtons(actions,weapon,targetSlot){if(weapon?.kind!=='weapon')return;for(const [slot,part] of Object.entries(weapon.parts||{})){if(!part)continue;const b=document.createElement('button');b.textContent=`${part.name||slot} 분리`;b.onclick=()=>detachWeaponPart(targetSlot,slot);actions.appendChild(b)}}", 'part lobby actions')

m = rep(m, "actions.appendChild(b);addRepair(actions,it);d.appendChild(actions)}eq.appendChild(d)}",
"actions.appendChild(b);addRepair(actions,it);addPartDetachButtons(actions,it,slot);d.appendChild(actions)}eq.appendChild(d)}", 'equipment detach buttons')
m = rep(m, "else if(['armor','helmet','backpack'].includes(it.kind)){const b=document.createElement('button');b.textContent='장착';b.onclick=()=>equipFromInventory(i,it.kind);actions.appendChild(b)}const st=",
"else if(['armor','helmet','backpack'].includes(it.kind)){const b=document.createElement('button');b.textContent='장착';b.onclick=()=>equipFromInventory(i,it.kind);actions.appendChild(b)}addPartAttachButtons(actions,it,meta.inventory,i);const st=", 'inventory part attach')
m = rep(m, "actions.appendChild(b);addRepair(actions,it);const sell=",
"actions.appendChild(b);addRepair(actions,it);addPartAttachButtons(actions,it,meta.stash,i);const sell=", 'stash part attach')
m = rep(m, "...['armor_light','armor_heavy','helmet','backpack','med','grenade'].map(k=>({name:GEAR[k].name,price:GEAR[k].price,meta:itemMeta(GEAR[k]),make:()=>makeGear(k)}))];",
"...['armor_light','armor_heavy','helmet','backpack','med','grenade'].map(k=>({name:GEAR[k].name,price:GEAR[k].price,meta:itemMeta(GEAR[k]),make:()=>makeGear(k)})),...Object.keys(WEAPON_PARTS).map(k=>({name:WEAPON_PARTS[k].name,price:WEAPON_PARTS[k].price,meta:itemMeta(WEAPON_PARTS[k]),make:()=>makePart(k)}))];", 'shop parts')

m = rep(m, "function camera(){const p=visualPlayer();if(!p)return{x:0,y:0};const kick=recoilKick,dx=Math.cos(p.angle)*kick,dy=Math.sin(p.angle)*kick;return{x:Math.max(0,Math.min(snap.worldW-canvas.width,p.x-canvas.width/2+dx)),y:Math.max(0,Math.min(snap.worldH-canvas.height,p.y-canvas.height/2+dy))}}",
"function camera(){const p=visualPlayer();if(!p)return{x:0,y:0};const kick=recoilKick,lead=p.scopeLead||0,dx=Math.cos(p.angle)*(kick+lead),dy=Math.sin(p.angle)*(kick+lead);return{x:Math.max(0,Math.min(snap.worldW-canvas.width,p.x-canvas.width/2+dx)),y:Math.max(0,Math.min(snap.worldH-canvas.height,p.y-canvas.height/2+dy))}}", 'scope camera lead')

old_ground = "function drawGround(cam){const p=snap.map?.palette||{},ground=p.ground||'#1b2223',a=p.gridA||'#1d2627',b=p.gridB||'#20292a';ctx.fillStyle=ground;ctx.fillRect(cam.x-10,cam.y-10,canvas.width+20,canvas.height+20);const sx=Math.floor(cam.x/80)*80,sy=Math.floor(cam.y/80)*80;for(let y=sy;y<cam.y+canvas.height+80;y+=80)for(let x=sx;x<cam.x+canvas.width+80;x+=80){ctx.fillStyle=((x/80+y/80)%2)?a:b;ctx.fillRect(x,y,78,78)}ctx.fillStyle=p.road||'#29363a';for(const r of snap.map?.roads||[])ctx.fillRect(r.x,r.y,r.w,r.h);ctx.fillStyle=p.line||'rgba(221,184,92,.16)';for(const r of snap.map?.roads||[]){if(r.w>r.h)ctx.fillRect(r.x,r.y+r.h/2-2,r.w,4);else ctx.fillRect(r.x+r.w/2-2,r.y,4,r.h)}}"
new_ground = "function drawGround(cam){const p=snap.map?.palette||{},ground=p.ground||'#1b2223',a=p.gridA||'#1d2627',b=p.gridB||'#20292a';ctx.fillStyle=ground;ctx.fillRect(cam.x-10,cam.y-10,canvas.width+20,canvas.height+20);const sx=Math.floor(cam.x/80)*80,sy=Math.floor(cam.y/80)*80;for(let y=sy;y<cam.y+canvas.height+80;y+=80)for(let x=sx;x<cam.x+canvas.width+80;x+=80){ctx.fillStyle=((x/80+y/80)%2)?a:b;ctx.fillRect(x,y,78,78)}ctx.fillStyle=p.road||'#29363a';for(const r of snap.map?.roads||[])ctx.fillRect(r.x,r.y,r.w,r.h);ctx.fillStyle=p.line||'rgba(221,184,92,.16)';for(const r of snap.map?.roads||[]){if(r.w>r.h)ctx.fillRect(r.x,r.y+r.h/2-2,r.w,4);else ctx.fillRect(r.x+r.w/2-2,r.y,4,r.h)}ctx.save();if(snap.map?.id==='research'){ctx.strokeStyle='rgba(104,232,196,.08)';ctx.lineWidth=1;for(let x=Math.floor(cam.x/160)*160;x<cam.x+canvas.width+160;x+=160){ctx.beginPath();ctx.moveTo(x,cam.y);ctx.lineTo(x,cam.y+canvas.height);ctx.stroke()}for(let y=Math.floor(cam.y/160)*160;y<cam.y+canvas.height+160;y+=160){ctx.beginPath();ctx.moveTo(cam.x,y);ctx.lineTo(cam.x+canvas.width,y);ctx.stroke()}}else if(snap.map?.id==='harbor'){ctx.strokeStyle='rgba(126,215,239,.09)';for(let y=Math.floor(cam.y/110)*110;y<cam.y+canvas.height+110;y+=110){ctx.beginPath();for(let x=cam.x-30;x<cam.x+canvas.width+30;x+=28){const yy=y+Math.sin((x+y)*.018)*4;if(x===cam.x-30)ctx.moveTo(x,yy);else ctx.lineTo(x,yy)}ctx.stroke()}}else{ctx.fillStyle='rgba(221,184,92,.06)';for(let x=Math.floor(cam.x/240)*240;x<cam.x+canvas.width+240;x+=240)ctx.fillRect(x,cam.y,8,canvas.height)}ctx.restore()}"
m = rep(m, old_ground, new_ground, 'map visual flavor')

old_obs = "function drawObstacles(cam){for(const o of snap.obstacles){if(o.x+o.w<cam.x-40||o.x>cam.x+canvas.width+40||o.y+o.h<cam.y-40||o.y>cam.y+canvas.height+40||!rectInVision(o))continue;ctx.fillStyle=obstacleColor(o.kind);ctx.fillRect(o.x,o.y,o.w,o.h);ctx.fillStyle='rgba(255,255,255,.055)';ctx.fillRect(o.x,o.y,o.w,3);ctx.strokeStyle='rgba(0,0,0,.42)';ctx.strokeRect(o.x,o.y,o.w,o.h)}}"
new_obs = "function drawObstacles(cam){for(const o of snap.obstacles){if(o.x+o.w<cam.x-40||o.x>cam.x+canvas.width+40||o.y+o.h<cam.y-40||o.y>cam.y+canvas.height+40||!rectInVision(o))continue;ctx.fillStyle=obstacleColor(o.kind);ctx.fillRect(o.x,o.y,o.w,o.h);if(o.kind==='water'){ctx.save();ctx.strokeStyle='rgba(120,220,240,.24)';ctx.lineWidth=2;for(let y=o.y+12;y<o.y+o.h;y+=26){ctx.beginPath();ctx.moveTo(o.x+8,y);ctx.lineTo(o.x+o.w-8,y);ctx.stroke()}ctx.restore()}else{ctx.fillStyle='rgba(255,255,255,.055)';ctx.fillRect(o.x,o.y,o.w,3)}ctx.strokeStyle='rgba(0,0,0,.42)';ctx.strokeRect(o.x,o.y,o.w,o.h)}}"
m = rep(m, old_obs, new_obs, 'water visuals')

old_cross = "function drawCrosshair(){if(!session)return;let cx=mouse.x,cy=mouse.y;if(TOUCH_MODE&&snap?.player){const cam=camera(),p=visualPlayer()||snap.player;cx=p.x-cam.x+touchAim.x*150;cy=p.y-cam.y+touchAim.y*150}ctx.save();ctx.translate(cx,cy);ctx.strokeStyle='rgba(225,242,247,.92)';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,0,7,0,Math.PI*2);ctx.moveTo(-13,0);ctx.lineTo(-5,0);ctx.moveTo(13,0);ctx.lineTo(5,0);ctx.moveTo(0,-13);ctx.lineTo(0,-5);ctx.moveTo(0,13);ctx.lineTo(0,5);ctx.stroke();ctx.restore()}"
new_cross = "function drawCrosshair(){if(!session)return;let cx=mouse.x,cy=mouse.y;if(TOUCH_MODE&&snap?.player){const cam=camera(),p=visualPlayer()||snap.player;cx=p.x-cam.x+touchAim.x*150;cy=p.y-cam.y+touchAim.y*150}const bloom=Math.min(17,(snap?.player?.recoil||0)*150),inner=5+bloom,outer=13+bloom;ctx.save();ctx.translate(cx,cy);ctx.strokeStyle='rgba(225,242,247,.92)';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,0,7+bloom*.25,0,Math.PI*2);ctx.moveTo(-outer,0);ctx.lineTo(-inner,0);ctx.moveTo(outer,0);ctx.lineTo(inner,0);ctx.moveTo(0,-outer);ctx.lineTo(0,-inner);ctx.moveTo(0,outer);ctx.lineTo(0,inner);ctx.stroke();ctx.restore()}"
m = rep(m, old_cross, new_cross, 'recoil crosshair')

m = rep(m, "$('#weaponName').textContent=p.weapon?.name||'무기 없음';$('#ammoText').textContent=p.weapon?`${p.weapon.ammo} / ${p.ammoReserve||0}`:'0 / 0';",
"$('#weaponName').textContent=p.weapon?.name||'무기 없음';$('#ammoText').textContent=p.weapon?`${p.weapon.ammo} / ${p.magCapacity||WEAPONS[p.weapon.type]?.mag||0} · 예비 ${p.ammoReserve||0}`:'0 / 0';", 'hud mag cap')
m = rep(m, "if(mapHud)mapHud.textContent=snap.map?.name||roomState?.mapName||'-';",
"if(mapHud)mapHud.textContent=`${snap.map?.name||roomState?.mapName||'-'}${snap.map?.trait?` · ${snap.map.trait}`:''}`;", 'hud map trait')
m = rep(m, "realtime.on('disconnect',()=>{if(session===realtime&&!lastResultHandled){lastResultHandled=true;session=null;if(document.pointerLockElement)document.exitPointerLock?.();showResult(false,{reason:'멀티 서버 연결 끊김',kills:snap?.player?.kills||0,lootValue:0})}})",
"realtime.on('disconnect',x=>{if(session===realtime&&!lastResultHandled){lastResultHandled=true;session=null;if(document.pointerLockElement)document.exitPointerLock?.();showResult(false,{reason:x?.reason||'멀티 서버 연결 끊김',kills:snap?.player?.kills||0,lootValue:0})}})", 'disconnect reason')
mp.write_text(m, encoding='utf-8')

print('v3.4.0 combat/parts/maps/reconnect patch applied')
