import {LocalSession,WebSocketSession} from './net.js';
import {WEAPONS,GEAR,AMMO_TIERS,AMMO_CALIBERS,AMMO_STACK_MAX} from './sim.js';
import {ACTIONS,emptyInput} from './protocol.js';

const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d',{alpha:false,desynchronized:true})||canvas.getContext('2d');
const TOUCH_MODE=matchMedia('(pointer: coarse)').matches||navigator.maxTouchPoints>0;
let touchMove={x:0,y:0,sprint:false},touchAim={x:1,y:0},touchInteract=false,touchReload=false;
const SAVE_KEY='deadDropMetaV21';
const cp=o=>JSON.parse(JSON.stringify(o));
const id=()=>`m${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`;
const makeWeapon=type=>({id:id(),kind:'weapon',type,name:WEAPONS[type].name,ammo:0,ammoTier:1,reserve:0,damage:WEAPONS[type].damage,value:WEAPONS[type].price});
const makeGear=key=>({id:id(),key,...cp(GEAR[key]),value:GEAR[key].price});
const ammoPrice=(caliber,tier,qty=AMMO_CALIBERS[caliber]?.pack||30)=>Math.round(qty*(AMMO_TIERS[tier]?.unitPrice||3));
const makeAmmo=(caliber,tier=1,qty=AMMO_CALIBERS[caliber]?.pack||30,starterIssue=false)=>({id:id(),kind:'ammo',caliber,tier,qty,name:`${AMMO_CALIBERS[caliber]?.name||caliber} T${tier} 탄약`,value:starterIssue?0:ammoPrice(caliber,tier,qty),starterIssue});
function metaAmmoMatch(a,b){return a?.kind==='ammo'&&b?.kind==='ammo'&&a.caliber===b.caliber&&(a.tier||1)===(b.tier||1)&&!!a.starterIssue===!!b.starterIssue}
function syncMetaAmmoValue(it){if(it?.kind!=='ammo')return it;it.qty=Math.max(0,Math.floor(Number(it.qty)||0));it.value=it.starterIssue?0:ammoPrice(it.caliber,it.tier||1,it.qty);return it}
function addMetaItemStacked(list,raw,maxSlots=Infinity){if(!raw)return 0;if(raw.kind!=='ammo'){if(list.length>=maxSlots)return 0;list.push(raw);return 1}let remaining=Math.max(0,Math.floor(Number(raw.qty)||0)),start=remaining;for(const stack of list){if(remaining<=0)break;if(!metaAmmoMatch(stack,raw)||(stack.qty||0)>=AMMO_STACK_MAX)continue;const add=Math.min(remaining,AMMO_STACK_MAX-(stack.qty||0));stack.qty=(stack.qty||0)+add;remaining-=add;syncMetaAmmoValue(stack)}while(remaining>0&&list.length<maxSlots){const add=Math.min(remaining,AMMO_STACK_MAX);list.push(syncMetaAmmoValue({...cp(raw),id:id(),qty:add}));remaining-=add}return start-remaining}
function compactMetaAmmo(list){const out=[];for(const it of list||[])addMetaItemStacked(out,it);return out}
function canMetaReceive(list,it,maxSlots=Infinity){if(!it)return false;if(it.kind!=='ammo')return list.length<maxSlots;return list.length<maxSlots||list.some(x=>metaAmmoMatch(x,it)&&(x.qty||0)<AMMO_STACK_MAX)}
function transferMetaItem(src,index,dst,maxSlots=Infinity){const it=src[index];if(!it)return 0;if(it.kind!=='ammo'){if(dst.length>=maxSlots)return 0;dst.push(src.splice(index,1)[0]);return 1}const moved=addMetaItemStacked(dst,it,maxSlots);if(moved<=0)return 0;it.qty-=moved;syncMetaAmmoValue(it);if(it.qty<=0)src.splice(index,1);return moved}

const defaultMeta=()=>({money:3200,visionLevel:3,callsign:`P-${Math.floor(1000+Math.random()*9000)}`,equipment:{primary:null,secondary:null,armor:null,helmet:null,backpack:null},inventory:[],stash:[makeWeapon('ar'),makeWeapon('pistol'),makeGear('armor_light'),makeGear('helmet'),makeGear('backpack'),makeGear('med'),makeGear('med'),makeGear('grenade'),makeGear('grenade'),makeAmmo('9mm',1),makeAmmo('5.56',1)]});
let meta=defaultMeta();try{const s=localStorage.getItem(SAVE_KEY);if(s)meta={...defaultMeta(),...JSON.parse(s)}}catch{}
if(!meta.equipment)meta.equipment=defaultMeta().equipment;if(!Array.isArray(meta.inventory))meta.inventory=[];if(!Array.isArray(meta.stash))meta.stash=[];if(!meta.callsign)meta.callsign=`P-${Math.floor(1000+Math.random()*9000)}`;
const save=()=>{try{localStorage.setItem(SAVE_KEY,JSON.stringify(meta))}catch{}};
function migrateAmmoEconomy(){if(meta.ammoEconomyV1)return;const items=[meta.equipment?.primary,meta.equipment?.secondary,...(meta.inventory||[]),...(meta.stash||[])].filter(Boolean),bonus=[];for(const it of items){if(it.kind==='weapon'){it.ammoTier=it.ammoTier||1;if((it.reserve||0)>0){bonus.push(makeAmmo(WEAPONS[it.type]?.caliber||'9mm',1,it.reserve));it.reserve=0}}else if(it.kind==='ammo'){it.caliber=it.caliber||WEAPONS[it.type]?.caliber||'9mm';it.tier=Math.max(1,Math.min(5,Number(it.tier)||1));it.qty=Math.max(0,Number(it.qty)||0);it.name=`${AMMO_CALIBERS[it.caliber]?.name||it.caliber} T${it.tier} 탄약`;it.value=it.value??ammoPrice(it.caliber,it.tier,it.qty)}}meta.stash.push(...bonus);meta.ammoEconomyV1=true;save()}
migrateAmmoEconomy();
meta.inventory=compactMetaAmmo(meta.inventory);meta.stash=compactMetaAmmo(meta.stash);save();
function hasBasicPistol(){
 const items=[meta.equipment?.primary,meta.equipment?.secondary,...(meta.inventory||[]),...(meta.stash||[])];
 return items.some(it=>it?.kind==='weapon'&&it.type==='pistol');
}
function ensureBasicPistol(){
 if(hasBasicPistol())return false;
 const w=makeWeapon('pistol');
 w.name='M9 권총 · 긴급 지급';
 w.value=0;
 w.starterIssue=true;
 meta.stash.push(w);
 addMetaItemStacked(meta.stash,makeAmmo('9mm',1,15,true));
 save();
 return true;
}
const money=n=>`${Math.round(n||0).toLocaleString()} G`;
function conditionRatio(it){if(it?.kind==='armor')return Math.max(0,Math.min(1,(it.armor??it.maxArmor??0)/(it.maxArmor||1)));if(it?.kind==='helmet')return Math.max(0,Math.min(1,(it.durability??it.maxDurability??0)/(it.maxDurability||1)));return 1}
function sellPrice(it){if(!it||it.starterIssue||(it.value||0)<=0)return 0;const rate=it.kind==='valuable'?1:it.kind==='ammo'?.75:it.kind==='weapon'?.65:.7;return Math.max(1,Math.round((it.value||0)*rate*(.55+.45*conditionRatio(it))))}
function repairInfo(it){if(!it||!['armor','helmet'].includes(it.kind))return null;const cur=it.kind==='armor'?(it.armor??it.maxArmor??0):(it.durability??it.maxDurability??0),max=it.kind==='armor'?(it.maxArmor||cur):(it.maxDurability||cur),missing=Math.max(0,max-cur),base=it.price||it.value||0;return{cur,max,missing,cost:missing>0?Math.max(1,Math.ceil(base*.6*(missing/Math.max(1,max)))):0}}
function repairItem(it){const r=repairInfo(it);if(!r||r.cost<=0)return;if(meta.money<r.cost)return alert('수리비가 부족합니다.');meta.money-=r.cost;if(it.kind==='armor')it.armor=it.maxArmor;else it.durability=it.maxDurability;save();renderLobby()}
function weaponSpec(type){const d=WEAPONS[type];return{damage:d.pellets?`${d.damage}×${d.pellets}`:String(d.damage),rpm:Math.round(60/d.rate),mag:d.mag,reload:d.reload.toFixed(2),range:d.range,recoil:d.recoil.toFixed(2),spread:(d.spread*57.2958).toFixed(1)}}
const slotNames={primary:'주무기',secondary:'보조무기',armor:'방탄복',helmet:'헬멧',backpack:'백팩'};
const equipKind={armor:'armor',helmet:'helmet',backpack:'backpack'};
const weaponDesc={pistol:'저렴한 반자동 보조무기',smg:'근거리 압박용 고연사 기관단총',ar:'근·중거리 범용 돌격소총',shotgun:'실내와 코너전에 강한 근접 화력',dmr:'중·장거리 정밀 사격용 고화력 소총'};
function itemName(it){return it?.name||'빈 슬롯'}
function itemMeta(it){if(!it)return'';if(it.kind==='weapon'){const w=weaponSpec(it.type);return`${weaponDesc[it.type]} · ${AMMO_CALIBERS[WEAPONS[it.type].caliber]?.name||WEAPONS[it.type].caliber} · 기본 DMG ${w.damage} · ${w.rpm} RPM · 탄창 ${it.ammo??0}/${WEAPONS[it.type].mag} · 현재 T${it.ammoTier||1}`};if(it.kind==='ammo'){const t=AMMO_TIERS[it.tier||1];return`${AMMO_CALIBERS[it.caliber]?.name||it.caliber} · T${it.tier||1} · ${it.qty||0}/${AMMO_STACK_MAX}발 · 해당 탄 사용 시 무기 피해 ×${(t?.damageMult||1).toFixed(2)}`};if(it.kind==='armor')return`몸통 피격 피해 일부 흡수 · 방탄 ${Math.round(it.armor??it.maxArmor??0)}/${it.maxArmor||0} · 손상 시 로비에서 수리`;if(it.kind==='helmet')return`머리 피격 피해 일부 흡수 · 내구 ${Math.round(it.durability??it.maxDurability??0)}/${it.maxDurability||0} · 손상 시 로비에서 수리`;if(it.kind==='backpack')return`휴대 가능 가방 슬롯을 ${it.capacity||8}칸으로 확장`;if(it.kind==='med')return`H키 · 2초 사용 · HP +${it.heal} · 사용 중 사격 불가`;if(it.kind==='grenade')return`G키 · 폭발 피해 ${it.damage||92} · 반경 ${it.radius||165}`;if(it.kind==='valuable')return`탈출 후 판매하는 전리품 · 평가 ${money(it.value)}`;return`평가 가치 ${money(it.value)}`}
function canEquipTo(it,slot){if(!it)return false;if(slot==='primary'||slot==='secondary')return it.kind==='weapon';return it.kind===equipKind[slot]}
function moveEquipToInventory(slot){const it=meta.equipment[slot];if(!it||meta.inventory.length>=12)return;meta.inventory.push(it);meta.equipment[slot]=null;save();renderLobby()}
function equipFromInventory(index,slot){const it=meta.inventory[index];if(!canEquipTo(it,slot))return;const old=meta.equipment[slot];meta.equipment[slot]=it;meta.inventory.splice(index,1);if(old)meta.inventory.push(old);save();renderLobby()}
function stashToInventory(i){if(!transferMetaItem(meta.stash,i,meta.inventory,12))return;save();renderLobby()}
function inventoryToStash(i){if(!transferMetaItem(meta.inventory,i,meta.stash))return;save();renderLobby()}
function sellFromInventory(i){const it=meta.inventory[i],price=sellPrice(it);if(!it||price<=0)return;meta.money+=price;meta.inventory.splice(i,1);save();renderLobby()}
function sellFromStash(i){const it=meta.stash[i],price=sellPrice(it);if(!it||price<=0)return;meta.money+=price;meta.stash.splice(i,1);save();renderLobby()}
function renderWeaponStats(){const root=$('#weaponStatsList');if(!root||root.childElementCount)return;for(const [type,d] of Object.entries(WEAPONS)){const w=weaponSpec(type),lo=Math.round(d.damage*AMMO_TIERS[1].damageMult),hi=Math.round(d.damage*AMMO_TIERS[5].damageMult),card=document.createElement('div');card.className='weaponStatCard';card.innerHTML=`<div class="weaponStatHead"><b>${d.name}</b><span>${money(d.price)}</span></div><div class="weaponStatGrid"><span>구경 <b>${AMMO_CALIBERS[d.caliber]?.name||d.caliber}</b></span><span>피해 <b>${lo}~${hi}</b></span><span>연사 <b>${w.rpm} RPM</b></span><span>탄창 <b>${w.mag}</b></span><span>재장전 <b>${w.reload}s</b></span><span>유효거리 <b>${w.range}</b></span><span>반동 <b>${w.recoil}</b></span></div>`;root.appendChild(card)}}

function renderLobby(){
 $('#moneyText').textContent=money(meta.money);$('#visionLevel').value=meta.visionLevel;$('#visionLevelText').textContent=meta.visionLevel;$('#raidInvCount').textContent=`${meta.inventory.length}/12`;
 const addRepair=(actions,it)=>{const ri=repairInfo(it);if(!ri)return;const rb=document.createElement('button');rb.className='repairBtn';rb.textContent=ri.cost>0?`수리 ${money(ri.cost)}`:'수리 완료';rb.disabled=ri.cost<=0;rb.onclick=()=>repairItem(it);actions.appendChild(rb)};
 const eq=$('#equipmentGrid');eq.innerHTML='';for(const slot of ['primary','secondary','armor','helmet','backpack']){const it=meta.equipment[slot],d=document.createElement('div');d.className='equipmentSlot'+(it?' filled':'');d.innerHTML=`<div class="slotLabel">${slotNames[slot]}</div><div class="slotTitle">${itemName(it)}</div><div class="slotMeta">${itemMeta(it)}</div>`;if(it){const actions=document.createElement('div');actions.style.display='flex';actions.style.gap='3px';actions.style.flexWrap='wrap';const b=document.createElement('button');b.textContent='인벤토리로';b.disabled=meta.inventory.length>=12;b.onclick=()=>moveEquipToInventory(slot);actions.appendChild(b);addRepair(actions,it);d.appendChild(actions)}eq.appendChild(d)}
 const inv=$('#raidInventory');inv.innerHTML='';for(let i=0;i<12;i++){const it=meta.inventory[i],d=document.createElement('div');d.className='inventorySlot';if(it){d.innerHTML=`<b>${itemName(it)}</b><span class="slotMeta">${itemMeta(it)}</span>`;const actions=document.createElement('div');actions.style.display='flex';actions.style.gap='3px';actions.style.flexWrap='wrap';if(it.kind==='weapon'){for(const [slot,label] of [['primary','주'],['secondary','보']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>equipFromInventory(i,slot);actions.appendChild(b)}}else if(['armor','helmet','backpack'].includes(it.kind)){const b=document.createElement('button');b.textContent='장착';b.onclick=()=>equipFromInventory(i,it.kind);actions.appendChild(b)}const st=document.createElement('button');st.textContent='창고';st.onclick=()=>inventoryToStash(i);actions.appendChild(st);addRepair(actions,it);const price=sellPrice(it),sell=document.createElement('button');sell.className='sellBtn';sell.textContent=price>0?`판매 +${money(price)}`:'판매 불가';sell.disabled=price<=0;sell.onclick=()=>sellFromInventory(i);actions.appendChild(sell);d.appendChild(actions)}inv.appendChild(d)}
 const stash=$('#stashList');stash.innerHTML='';if(!meta.stash.length)stash.innerHTML='<div class="muted">창고가 비어 있습니다.</div>';meta.stash.forEach((it,i)=>{const d=document.createElement('div');d.className='stashItem';const price=sellPrice(it),ri=repairInfo(it);d.innerHTML=`<b>${itemName(it)}</b><div class="meta">${itemMeta(it)}<br>평가 ${money(it.value||0)} · 판매 ${money(price)}${ri&&ri.missing>0?` · 수리비 ${money(ri.cost)}`:''}</div>`;const actions=document.createElement('div');actions.className='stashActions';const b=document.createElement('button');b.textContent='출격 인벤토리로';b.disabled=!canMetaReceive(meta.inventory,it,12);b.onclick=()=>stashToInventory(i);actions.appendChild(b);addRepair(actions,it);const sell=document.createElement('button');sell.className='sellBtn';sell.textContent=price>0?'판매':'판매 불가';sell.disabled=price<=0;sell.onclick=()=>sellFromStash(i);actions.appendChild(sell);d.appendChild(actions);stash.appendChild(d)});
 const shop=$('#shopList');shop.innerHTML='';const products=[...Object.keys(WEAPONS).map(k=>({name:WEAPONS[k].name,price:WEAPONS[k].price,meta:`빈 탄창 · ${AMMO_CALIBERS[WEAPONS[k].caliber].name}`,make:()=>makeWeapon(k)})),...['armor_light','armor_heavy','helmet','backpack','med','grenade'].map(k=>({name:GEAR[k].name,price:GEAR[k].price,meta:itemMeta(GEAR[k]),make:()=>makeGear(k)}))];for(const p of products){const r=document.createElement('div');r.className='shopItem';r.innerHTML=`<b>${p.name}</b><div class="meta">${p.meta||''}${p.meta?' · ':''}${money(p.price)}</div>`;const b=document.createElement('button');b.textContent='창고로 구매';b.onclick=()=>{if(meta.money<p.price)return alert('자금이 부족합니다.');meta.money-=p.price;meta.stash.push(p.make());save();renderLobby()};r.appendChild(b);shop.appendChild(r)}
 const ammoRoot=$('#ammoShopList');ammoRoot.innerHTML='';for(const [cal,c] of Object.entries(AMMO_CALIBERS)){const group=document.createElement('div');group.className='ammoGroup';group.innerHTML=`<div class="ammoHead"><b>${c.name}</b><span>${c.pack}발 묶음</span></div>`;const tiers=document.createElement('div');tiers.className='ammoTiers';for(let tier=1;tier<=5;tier++){const t=AMMO_TIERS[tier],price=ammoPrice(cal,tier,c.pack),b=document.createElement('button');b.dataset.tier=tier;b.innerHTML=`T${tier}<br>${money(price)}<br>×${t.damageMult.toFixed(2)}`;b.onclick=()=>{if(meta.money<price)return alert('자금이 부족합니다.');meta.money-=price;addMetaItemStacked(meta.stash,makeAmmo(cal,tier));save();renderLobby()};tiers.appendChild(b)}group.appendChild(tiers);ammoRoot.appendChild(group)}
 renderWeaponStats();$('#callsignInput').value=meta.callsign;$('#raidBtn').disabled=!meta.equipment.primary||(!LOCAL_MODE&&!multiplayerFallback&&roomState?.joinable===false);
}
$('#visionLevel').addEventListener('input',e=>{meta.visionLevel=Number(e.target.value);$('#visionLevelText').textContent=meta.visionLevel;save()});$('#callsignInput').addEventListener('input',e=>{meta.callsign=(e.target.value||'PLAYER').slice(0,18);save()});

const LOCAL_MODE=new URLSearchParams(location.search).has('local');const WS_URL=`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/realtime`;let realtime=null,roomState=null,pendingDeparture=null,multiplayerAvailable=false,multiplayerFallback=false;
let session=null,snap=null,input=emptyInput(),keys=new Set(),mouse={x:640,y:360},lastResultHandled=false,audioCtx=null;
let killFeed=[],soundMarks=[],fx=[],shake=0,recoilKick=0,hitMarkerT=0,hitHead=false,hurtFlashT=0,actorHitFlash=new Map(),renderActors=new Map(),lastSnapshotAt=performance.now(),lastHudAt=0,lastReloadValue=0,lastReloadWeapon=null;
let hudBagKey='',hudEqKey='',hudLootKey='';const hitMarkerEl=$('#hitMarker');
const audioSampleUrls={reloadGeneric:'./assets/audio/reload-generic.wav',reloadGeneric2:'./assets/audio/reload-generic2.wav',reloadPistol:'./assets/audio/reload-pistol.wav',reloadRifle:'./assets/audio/reload-rifle.wav',reloadShotgun:'./assets/audio/reload-shotgun.wav'};
const audioSamples={};let audioLoadPromise=null;
async function loadAudioSamples(){if(!audioCtx)return;if(audioLoadPromise)return audioLoadPromise;audioLoadPromise=Promise.all(Object.entries(audioSampleUrls).map(async([key,url])=>{try{const r=await fetch(url,{cache:'force-cache'});if(!r.ok)throw new Error(String(r.status));audioSamples[key]=await audioCtx.decodeAudioData(await r.arrayBuffer())}catch(e){console.warn('audio sample fallback',key,e)}}));return audioLoadPromise}
function ensureAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();loadAudioSamples()}
function playSample(key,volume=1,rate=1){const buf=audioSamples[key];if(!audioCtx||!buf)return false;const src=audioCtx.createBufferSource(),g=audioCtx.createGain();src.buffer=buf;src.playbackRate.value=rate*(.985+Math.random()*.03);g.gain.value=Math.max(.001,volume);src.connect(g).connect(audioCtx.destination);src.start();return true}
let sharedNoiseBuffer=null;function getNoiseBuffer(){if(!audioCtx)return null;if(sharedNoiseBuffer&&sharedNoiseBuffer.sampleRate===audioCtx.sampleRate)return sharedNoiseBuffer;const n=Math.floor(audioCtx.sampleRate*.28),buf=audioCtx.createBuffer(1,n,audioCtx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<n;i++)data[i]=Math.random()*2-1;sharedNoiseBuffer=buf;return buf}
function noiseBurst(duration=.06,volume=.04,low=160,high=900){if(!audioCtx)return;const buf=getNoiseBuffer();if(!buf)return;const src=audioCtx.createBufferSource(),f=audioCtx.createBiquadFilter(),g=audioCtx.createGain(),now=audioCtx.currentTime,d=Math.min(duration,.25),maxOffset=Math.max(0,buf.duration-d-.001);src.buffer=buf;f.type='bandpass';f.frequency.value=(low+high)/2;f.Q.value=.65;g.gain.setValueAtTime(Math.max(.0001,volume),now);g.gain.exponentialRampToValueAtTime(.0001,now+d);src.connect(f).connect(g).connect(audioCtx.destination);src.start(now,Math.random()*maxOffset,d)}
function shotSound(type,volume=1){if(!audioCtx)return;const d={pistol:[.035,360],smg:[.026,430],ar:[.045,300],shotgun:[.075,170],dmr:[.06,220]}[type]||[.04,300];noiseBurst(type==='shotgun'?.10:.065,d[0]*volume,70,d[1]*3);const o=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime;o.type='square';o.frequency.setValueAtTime(d[1],now);o.frequency.exponentialRampToValueAtTime(55,now+.055);g.gain.setValueAtTime(d[0]*.5*volume,now);g.gain.exponentialRampToValueAtTime(.001,now+.07);o.connect(g).connect(audioCtx.destination);o.start();o.stop(now+.08)}
function reloadSound(type){if(!audioCtx)return;const key=type==='shotgun'?'reloadShotgun':type==='ar'||type==='dmr'?'reloadRifle':'reloadPistol';if(playSample(key,.58,type==='smg'?1.08:1))return;playSample(type==='ar'||type==='dmr'?'reloadGeneric2':'reloadGeneric',.5,1)}
function explosionSound(volume=1){noiseBurst(.18,.10*volume,45,500)}
function footstepSound(loud=false,volume=1){if(!audioCtx)return;noiseBurst(loud?.045:.022,(loud?.032:.014)*volume,55,loud?260:190);const o=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime;o.type='sine';o.frequency.setValueAtTime(loud?92:120,now);o.frequency.exponentialRampToValueAtTime(48,now+(loud?.07:.045));g.gain.setValueAtTime((loud?.035:.018)*volume,now);g.gain.exponentialRampToValueAtTime(.001,now+(loud?.08:.055));o.connect(g).connect(audioCtx.destination);o.start();o.stop(now+.09)}
function currentPlayer(){return snap?.player}
function syncRenderActors(s){const seen=new Set();for(const a of s.actors||[]){seen.add(a.id);let r=renderActors.get(a.id);if(!r){r={x:a.x,y:a.y,angle:a.angle,tx:a.x,ty:a.y,ta:a.angle};renderActors.set(a.id,r)}r.tx=a.x;r.ty=a.y;r.ta=a.angle}for(const id of [...renderActors.keys()])if(!seen.has(id))renderActors.delete(id)}
function processSnapshot(s){const nextReload=s.player?.reload||0,nextWeapon=s.player?.weapon?.type||null;if(nextReload>0&&(lastReloadValue<=0||nextWeapon!==lastReloadWeapon))reloadSound(nextWeapon);lastReloadValue=nextReload;lastReloadWeapon=nextWeapon;snap=s;lastSnapshotAt=performance.now();syncRenderActors(s);if(s.room)roomState=s.room;if(s.openContainer&&document.pointerLockElement===canvas)document.exitPointerLock?.();const now=performance.now();if(now-lastHudAt>=90||s.result||s.openContainer||nextReload>0){lastHudAt=now;renderHUD()}if(s.result&&!lastResultHandled)handleResult(s.result)}
function enterRaid(activeSession){meta.equipment={primary:null,secondary:null,armor:null,helmet:null,backpack:null};meta.inventory=[];save();renderLobby();$('#lobby').classList.add('hidden');$('#raid').classList.remove('hidden');$('#raid').classList.remove('mobileBagOpen');lastResultHandled=false;killFeed=[];soundMarks=[];fx=[];actorHitFlash.clear();renderActors.clear();hurtFlashT=0;lastReloadValue=0;lastReloadWeapon=null;hudBagKey='';hudEqKey='';hudLootKey='';input=emptyInput();session=activeSession;canvas.focus()}
function startRaid(){if(!meta.equipment.primary)return;ensureAudio();const departure={name:meta.callsign||'PLAYER',equipment:cp(meta.equipment),inventory:cp(meta.inventory),visionLevel:meta.visionLevel};if(LOCAL_MODE||multiplayerFallback||!realtime?.connected){const local=new LocalSession(departure);local.on('snapshot',processSnapshot);local.on('event',handleEvent);enterRaid(local);return}if(roomState?.joinable===false)return alert(roomState?.entryClosed?'현재 RAID는 종료 1분 전이라 신규 참가가 마감되었습니다. 다음 RAID를 기다려주세요.':'현재 RAID가 8명으로 가득 찼습니다.');pendingDeparture=departure;$('#raidBtn').disabled=true;$('#roomStateText').textContent='현재 RAID 참가 요청 중...';realtime.join(departure)}
$('#raidBtn').onclick=startRaid;
function handleResult(r){lastResultHandled=true;if(document.pointerLockElement)document.exitPointerLock?.();input.shoot=false;keys.clear();if(session===realtime)realtime.leave();else session?.close();session=null;if(r.status==='extracted'){meta.equipment=r.equipment||{primary:null,secondary:null,armor:null,helmet:null,backpack:null};const cap=12,items=compactMetaAmmo(r.items||[]);meta.inventory=items.slice(0,cap);for(const it of items.slice(cap))addMetaItemStacked(meta.stash,it);save()}showResult(r.status==='extracted',r)}
function showResult(ok,r){const p=$('#resultPanel');p.classList.remove('hidden');p.innerHTML=`<div class="resultCard"><h2 class="${ok?'success':'failed'}">${ok?'EXTRACTED':'RAID LOST'}</h2><p>${ok?`탈출 성공 · ${r.reason}`:`${r.reason} · 출격 장비와 전리품 상실`}</p><p>처치 ${r.kills||0} · 회수품 평가 ${money(r.lootValue||0)} · 자동 현금화 없음</p><button id="backLobby" class="primary">로비로 돌아가기</button></div>`;$('#backLobby').onclick=()=>{p.classList.add('hidden');$('#raid').classList.add('hidden');$('#lobby').classList.remove('hidden');snap=null;ensureBasicPistol();renderLobby()}}
$('#abandonBtn').onclick=()=>{if(!session)return;if(confirm('출격 장비와 전리품을 모두 포기할까요?')){if(document.pointerLockElement)document.exitPointerLock?.();input.shoot=false;keys.clear();if(session===realtime)realtime.leave();else session.close();session=null;lastResultHandled=true;$('#raid').classList.add('hidden');$('#lobby').classList.remove('hidden');snap=null;ensureBasicPistol();renderLobby()}};

function renderRoomStatus(){
 const raidBtn=$('#raidBtn');
 if(LOCAL_MODE||multiplayerFallback){
   $('#roomIdText').textContent=LOCAL_MODE?'LOCAL':'LOCAL FALLBACK';$('#roomMap').textContent=snap?.map?.name||'로컬 순환맵';$('#roomHumans').textContent='1 / 1';$('#roomAi').textContent=snap?.aliveAI??7;$('#roomTime').textContent='--:--';
   const st=$('#roomStateText');st.className='roomState';st.textContent=LOCAL_MODE?'로컬 테스트 모드':'멀티 서버 연결 대기 중 · 현재는 로컬 출격 가능';raidBtn.textContent='현재 RAID 참가';if(!session)raidBtn.disabled=!meta.equipment.primary;return
 }
 const r=roomState;if(!r){$('#roomStateText').textContent=realtime?.connected?'방 정보 수신 중...':'멀티 서버 연결 중...';return}
 const left=Math.max(0,(r.endsAt-Date.now())/1000),m=Math.floor(left/60),sec=Math.floor(left%60),timeText=`${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`,entryClosed=r.entryClosed===true||left<=60;
 $('#roomIdText').textContent=r.roomId;$('#roomMap').textContent=r.mapName||'-';$('#roomHumans').textContent=`${r.humans} / ${r.capacity}`;$('#roomAi').textContent=r.ai;$('#roomTime').textContent=timeText;
 const st=$('#roomStateText');
 if(entryClosed){st.className='roomState full';st.textContent=`신규 참가 마감 · 다음 RAID ${timeText} 후 시작`;raidBtn.textContent='신규 참가 마감';if(!session)raidBtn.disabled=true;return}
 if(!r.joinable){st.className='roomState full';st.textContent='현재 방 FULL · 자리가 비면 참가 가능합니다.';raidBtn.textContent='현재 RAID FULL';if(!session)raidBtn.disabled=true;return}
 st.className='roomState live';st.textContent='중간 참가 가능 · 빈 인간 슬롯은 AI가 보충합니다.';raidBtn.textContent='현재 RAID 참가';if(!session)raidBtn.disabled=!meta.equipment.primary
}
function setupRealtime(){if(LOCAL_MODE){multiplayerFallback=true;$('#netText').textContent='LOCAL TEST MODE';return}realtime=new WebSocketSession(WS_URL);const fallbackTimer=setTimeout(()=>{if(!multiplayerAvailable&&!session){multiplayerFallback=true;$('#netText').textContent='MULTIPLAYER OFFLINE · LOCAL';renderRoomStatus();renderLobby()}},2500);realtime.on('connection',x=>{if(x.connected){clearTimeout(fallbackTimer);multiplayerAvailable=true;multiplayerFallback=false;$('#netText').textContent='MULTIPLAYER CONNECTED'}else{$('#netText').textContent=multiplayerFallback?'MULTIPLAYER OFFLINE · LOCAL':'MULTIPLAYER RECONNECTING'}renderRoomStatus();renderLobby()});realtime.on('status',r=>{roomState=r;multiplayerAvailable=true;multiplayerFallback=false;renderRoomStatus();renderLobby()});realtime.on('joined',()=>{if(!pendingDeparture)return;pendingDeparture=null;enterRaid(realtime)});realtime.on('join_denied',m=>{pendingDeparture=null;alert(m.reason||'현재 RAID에 참가할 수 없습니다.');renderLobby();renderRoomStatus()});realtime.on('snapshot',s=>{if(session===realtime)processSnapshot(s)});realtime.on('event',e=>{if(session===realtime)handleEvent(e)});realtime.on('disconnect',()=>{if(session===realtime&&!lastResultHandled){lastResultHandled=true;session=null;if(document.pointerLockElement)document.exitPointerLock?.();showResult(false,{reason:'멀티 서버 연결 끊김',kills:snap?.player?.kills||0,lootValue:0})}})}
setInterval(renderRoomStatus,250);

function eventOnScreen(e){if(!snap?.player)return false;return Math.hypot(e.x-snap.player.x,e.y-snap.player.y)<1000}
function handleEvent(e){
 if(e.type==='shot'){if(eventOnScreen(e)){const self=e.actor===snap?.playerId,visible=self||snap?.actors?.some(a=>a.id===e.actor);shotSound(e.weapon,self?1:.42);if(visible){const ang=e.angle??0;fx.push({kind:'muzzle',x:e.x+Math.cos(ang)*25,y:e.y+Math.sin(ang)*25,angle:ang,self,t:self?0.115:0.095,max:self?0.115:0.095});}if(self){recoilKick=Math.min(11,recoilKick+(e.recoil||2)*1.35);shake=Math.max(shake,(e.recoil||2)*.7);fx.push({kind:'casing',x:e.x,y:e.y,vx:(Math.random()-.5)*80,vy:-40-Math.random()*45,t:.5,max:.5})}}}
 if(e.type==='impact'&&eventOnScreen(e))fx.push({kind:'impact',x:e.x,y:e.y,t:.18,max:.18});
 if(e.type==='explosion'){if(eventOnScreen(e)){explosionSound(.8);shake=Math.max(shake,10);for(let i=0;i<16;i++)fx.push({kind:'spark',x:e.x,y:e.y,vx:(Math.random()-.5)*380,vy:(Math.random()-.5)*380,t:.45,max:.45})}}
 if(e.type==='hit'){actorHitFlash.set(e.target,{t:.16,max:.16,headshot:!!e.headshot});const ra=renderActors.get(e.target);if(ra&&e.target!==snap?.playerId)fx.push({kind:'damage',x:ra.x,y:ra.y-23,text:`-${e.damage||0}`,t:.55,max:.55});if(e.source===snap?.playerId){hitMarkerT=.16;hitHead=!!e.headshot;shake=Math.max(shake,e.headshot?3:1.5)}if(e.target===snap?.playerId){hurtFlashT=.24;shake=Math.max(shake,7)}}
 if(e.type==='kill'){killFeed.unshift(`${e.killer}  ▸  ${e.victim}`);killFeed=killFeed.slice(0,5);renderKillFeed()}
 if(e.type==='self_step')footstepSound(!!e.loud,e.loud?1:.72);if(e.type==='heard'){const life=e.kind==='footstep'?0.95:e.kind==='gunshot'?1.45:e.kind==='explosion'?1.7:1.1;if(e.kind==='footstep')footstepSound(!!e.loud,e.intensity==='near'?.72:e.intensity==='mid'?.48:.28);soundMarks.push({angle:e.angle,kind:e.kind||'sound',loud:!!e.loud,intensity:e.intensity||'mid',t:life,max:life});if(soundMarks.length>18)soundMarks.splice(0,soundMarks.length-18)}
 if(e.type==='loot')toast(`획득: ${e.item}`);if(e.type==='discard')toast(`버림: ${e.item}`);if(e.type==='equip')toast(`장착: ${e.item}`);if(e.type==='door')toast(`${e.name} ${e.open?'열림':'닫힘'}`);if(e.type==='door_blocked')toast(`${e.name} · 사람이 있어 닫을 수 없음`);if(e.type==='heal_start'&&e.actor===snap?.playerId)toast('치료 시작 · 2초');if(e.type==='heal'&&e.actor===snap?.playerId)toast(`치료 완료 +${e.amount||0} HP`);
}
function renderKillFeed(){$('#killFeed').innerHTML=killFeed.map(x=>`<div class="killMsg">${x}</div>`).join('')}
function toast(t){const el=$('#interactHint'),old=el.textContent;el.textContent=t;clearTimeout(toast.t);toast.t=setTimeout(()=>el.textContent=old,1000)}

function itemSub(it){return itemMeta(it)}
function renderHUD(){if(!snap?.player)return;const p=snap.player;$('#hpText').textContent=Math.ceil(p.hp);$('#hpBar').style.width=`${Math.max(0,p.hp/p.maxHp*100)}%`;$('#armorText').textContent=Math.ceil(p.armor);$('#armorBar').style.width=`${Math.max(0,p.maxArmor?p.armor/p.maxArmor*100:0)}%`;$('#weaponName').textContent=p.weapon?.name||'무기 없음';$('#ammoText').textContent=p.weapon?`${p.weapon.ammo} / ${p.ammoReserve||0}`:'0 / 0';$('#fireMode').textContent=p.weapon?`${WEAPONS[p.weapon.type].auto?'AUTO':'SEMI'} · T${p.weapon.ammoTier||1}`:'-';const m=Math.floor(snap.timeLeft/60),s=Math.floor(snap.timeLeft%60);$('#raidTimer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#visionHudText').textContent=p.visionLevel;const mapHud=$('#mapHud');if(mapHud)mapHud.textContent=snap.map?.name||roomState?.mapName||'-';$('#killCount').textContent=p.kills;$('#aliveCount').textContent=snap.aliveAI;$('#bagCount').textContent=`${p.inventory.length}/${p.bagCapacity}`;$('#lootValue').textContent=money(p.inventory.reduce((a,b)=>a+(b.value||0),0));$('#grenadeCount').textContent=p.inventory.filter(i=>i.kind==='grenade').length;$('#medCount').textContent=p.inventory.filter(i=>i.kind==='med').length;$('#sprintHud').classList.toggle('hidden',!p.sprinting);renderBag();renderRaidEquipment();renderLoot()}
function renderRaidEquipment(){const slots=['primary','secondary','armor','helmet','backpack'],key=snap.player.weaponSlot+'|'+slots.map(k=>`${k}:${snap.player.gear[k]?.id||''}`).join('|');if(key===hudEqKey)return;hudEqKey=key;const g=$('#raidEquipment');g.innerHTML='';for(const slot of slots){const it=snap.player.gear[slot],d=document.createElement('div'),hotkey=slot==='primary'?'[1] ':slot==='secondary'?'[2] ':'';d.className='raidEqSlot';if(slot===snap.player.weaponSlot&&(slot==='primary'||slot==='secondary')){d.style.borderColor='rgba(116,210,255,.9)';d.style.boxShadow='0 0 0 1px rgba(116,210,255,.25) inset'}d.innerHTML=`<b>${hotkey}${slotNames[slot]}</b><br>${it?itemName(it):'<span class="muted">비어 있음</span>'}`;g.appendChild(d)}}
function renderBag(){const inv=snap.player.inventory,key=snap.player.bagCapacity+'|'+inv.map(it=>`${it.id}:${it.ammo??''}:${it.qty??''}:${it.tier??''}:${it.ammoTier??''}`).join(',');if(key===hudBagKey)return;hudBagKey=key;const g=$('#bagGrid');g.innerHTML='';for(let i=0;i<snap.player.bagCapacity;i++){const it=inv[i],d=document.createElement('div');d.className='bagSlot';if(it){d.innerHTML=`<b>${itemName(it)}</b><small>${itemSub(it)}</small>`;const actions=document.createElement('div');actions.style.display='flex';actions.style.gap='4px';actions.style.flexWrap='wrap';if(['weapon','armor','helmet','backpack'].includes(it.kind)){const b=document.createElement('button');b.textContent='장착';b.onpointerdown=e=>{e.preventDefault();e.stopPropagation();session?.sendAction({type:ACTIONS.EQUIP_BAG,slot:i})};actions.appendChild(b)}const drop=document.createElement('button');drop.textContent='버리기';drop.className='danger';drop.title='이 아이템을 RAID에서 영구 삭제';drop.onpointerdown=e=>{e.preventDefault();e.stopPropagation();session?.sendAction({type:ACTIONS.DISCARD_ITEM,itemId:it.id})};actions.appendChild(drop);d.appendChild(actions)}g.appendChild(d)}}
function canRaidReceive(it,p){if(!it||!p)return false;if(it.kind!=='ammo')return p.inventory.length<p.bagCapacity;return p.inventory.length<p.bagCapacity||p.inventory.some(x=>metaAmmoMatch(x,it)&&(x.qty||0)<AMMO_STACK_MAX)}
function renderLoot(){const p=$('#lootPanel'),c=snap.openContainer;if(!c){if(hudLootKey){hudLootKey='';p.classList.add('hidden')}return}const key=c.id+'|'+c.items.map(i=>`${i.id}:${i.qty??''}:${i.tier??''}`).join(',')+'|'+snap.player.inventory.map(i=>`${i.id}:${i.qty??''}`).join(',')+'/'+snap.player.bagCapacity;if(key===hudLootKey)return;hudLootKey=key;p.classList.remove('hidden');p.innerHTML=`<div style="display:flex;justify-content:space-between"><b>${c.kind==='corpse'?`시체 · ${c.ownerName}`:'보급 상자'}</b><button id="closeLoot">×</button></div><div class="meta" style="margin:5px 0">가까이 있어야 루팅창이 유지됩니다.</div><div id="lootRows"></div>`;$('#closeLoot').onpointerdown=e=>{e.preventDefault();e.stopPropagation();session?.sendAction({type:ACTIONS.CLOSE_CONTAINER})};const rows=p.querySelector('#lootRows');if(!c.items.length)rows.innerHTML='<div class="muted" style="padding:12px">비어 있음</div>';for(const it of c.items){const r=document.createElement('div');r.className='lootRow';r.innerHTML=`<div><b>${itemName(it)}</b><small>${itemSub(it)}</small></div>`;const b=document.createElement('button');b.textContent='획득';b.disabled=!canRaidReceive(it,snap.player);b.onpointerdown=e=>{e.preventDefault();e.stopPropagation();session?.sendAction({type:ACTIONS.LOOT,itemId:it.id,containerId:c.id})};r.appendChild(b);rows.appendChild(r)}}
const progressBox=$('#openProgress'),progressFill=$('#openProgressFill'),progressText=$('#openProgressText');progressFill.style.width='100%';progressFill.style.transformOrigin='left center';progressFill.style.willChange='transform';function renderProgress(now=performance.now()){if(!snap?.player){progressBox.classList.add('hidden');return}const age=Math.min(.12,Math.max(0,(now-lastSnapshotAt)/1000)),show=(pct,text)=>{progressBox.classList.remove('hidden');progressFill.style.transform=`scaleX(${Math.max(0,Math.min(1,pct))})`;progressText.textContent=text};const healBase=snap.player.healTimer||0;if(healBase>0){const heal=Math.max(0,healBase-age),dur=snap.player.healDuration||2;show(1-heal/dur,`치료키트 사용중 · ${heal.toFixed(1)}초`);return}const reloadBase=snap.player.reload||0,weaponType=snap.player.weapon?.type;if(reloadBase>0&&weaponType&&WEAPONS[weaponType]){const reload=Math.max(0,reloadBase-age),dur=WEAPONS[weaponType].reload||1;show(1-reload/dur,`재장전 중 · ${reload.toFixed(1)}초`);return}const q=snap.interaction;if(q){const progress=Math.min(q.duration,q.progress+(keys.has('e')?age:0)),left=Math.max(0,q.duration-progress);show(progress/q.duration,q.kind==='extract'?`탈출 중 ${left.toFixed(1)}초`:`상자 여는 중 ${left.toFixed(1)}초`);return}progressBox.classList.add('hidden')}

function updateRenderActors(dt){for(const [id,r] of renderActors){const d=Math.hypot(r.tx-r.x,r.ty-r.y);if(d>180){r.x=r.tx;r.y=r.ty;r.angle=r.ta;continue}const k=1-Math.exp(-dt*(id===snap?.playerId?34:22));r.x+=(r.tx-r.x)*k;r.y+=(r.ty-r.y)*k;r.angle+=angleDelta(r.ta,r.angle)*k}}
function visualPlayer(){const p=snap?.player,r=p&&renderActors.get(snap.playerId);return p&&r?{...p,x:r.x,y:r.y,angle:r.angle}:p}
function camera(){const p=visualPlayer();if(!p)return{x:0,y:0};const kick=recoilKick,dx=Math.cos(p.angle)*kick,dy=Math.sin(p.angle)*kick;return{x:Math.max(0,Math.min(snap.worldW-canvas.width,p.x-canvas.width/2+dx)),y:Math.max(0,Math.min(snap.worldH-canvas.height,p.y-canvas.height/2+dy))}}
function onScreen(x,y,cam,pad=80){return x>cam.x-pad&&x<cam.x+canvas.width+pad&&y>cam.y-pad&&y<cam.y+canvas.height+pad}
function visionShape(){const p=snap?.player;if(!p)return null;const near=190+p.visionLevel*34,far=near+430+p.visionLevel*58;return{p,near,far,half:1.05}}
function angleDelta(a,b){return Math.atan2(Math.sin(a-b),Math.cos(a-b))}
function pointInVision(x,y){const v=visionShape();if(!v)return false;const dx=x-v.p.x,dy=y-v.p.y,d=Math.hypot(dx,dy);if(d<=v.near)return true;if(d>v.far)return false;return Math.abs(angleDelta(Math.atan2(dy,dx),v.p.angle))<=v.half}
function rectInVision(o){const v=visionShape();if(!v)return false;const px=Math.max(o.x,Math.min(v.p.x,o.x+o.w)),py=Math.max(o.y,Math.min(v.p.y,o.y+o.h));if(Math.hypot(px-v.p.x,py-v.p.y)<=v.near)return true;const pts=[[o.x,o.y],[o.x+o.w,o.y],[o.x,o.y+o.h],[o.x+o.w,o.y+o.h],[o.x+o.w/2,o.y+o.h/2],[px,py]];return pts.some(([x,y])=>pointInVision(x,y))}
let lastDraw=performance.now();function draw(now=performance.now()){requestAnimationFrame(draw);const dt=Math.min(.033,Math.max(.001,(now-lastDraw)/1000));lastDraw=now;recoilKick*=Math.pow(.78,dt*60);shake*=Math.pow(.86,dt*60);hitMarkerT=Math.max(0,hitMarkerT-dt);hurtFlashT=Math.max(0,hurtFlashT-dt);for(const [id,h] of actorHitFlash){h.t-=dt;if(h.t<=0)actorHitFlash.delete(id)}soundMarks.forEach(s=>s.t-=dt);soundMarks=soundMarks.filter(s=>s.t>0);for(const f of fx){f.t-=dt;if(f.vx!=null){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=120*dt}}fx=fx.filter(f=>f.t>0);hitMarkerEl.style.opacity=hitMarkerT>0?'1':'0';hitMarkerEl.style.filter=hitHead?'sepia(1) saturate(4) hue-rotate(5deg)':'none';if(!snap)return;renderProgress(now);updateRenderActors(dt);let cam=camera();if(shake>.2){cam={x:cam.x+(Math.random()-.5)*shake,y:cam.y+(Math.random()-.5)*shake}}ctx.fillStyle='#030506';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(-cam.x,-cam.y);drawGround(cam);drawZones(cam);drawExtracts(cam);drawObstacles(cam);drawDoors(cam);drawCrates(cam);drawCorpses(cam);drawActors(cam);drawGrenades(cam);drawFxWorld(cam);ctx.restore();drawDarkness(cam);ctx.save();ctx.translate(-cam.x,-cam.y);drawBullets(cam);ctx.restore();drawSprintOverlay();drawDamageOverlay();drawSoundIndicators();drawCrosshair();}
function drawGround(cam){const p=snap.map?.palette||{},ground=p.ground||'#1b2223',a=p.gridA||'#1d2627',b=p.gridB||'#20292a';ctx.fillStyle=ground;ctx.fillRect(cam.x-10,cam.y-10,canvas.width+20,canvas.height+20);const sx=Math.floor(cam.x/80)*80,sy=Math.floor(cam.y/80)*80;for(let y=sy;y<cam.y+canvas.height+80;y+=80)for(let x=sx;x<cam.x+canvas.width+80;x+=80){ctx.fillStyle=((x/80+y/80)%2)?a:b;ctx.fillRect(x,y,78,78)}ctx.fillStyle=p.road||'#29363a';for(const r of snap.map?.roads||[])ctx.fillRect(r.x,r.y,r.w,r.h);ctx.fillStyle=p.line||'rgba(221,184,92,.16)';for(const r of snap.map?.roads||[]){if(r.w>r.h)ctx.fillRect(r.x,r.y+r.h/2-2,r.w,4);else ctx.fillRect(r.x+r.w/2-2,r.y,4,r.h)}}
function drawZones(cam){for(const z of snap.zones){if(z.x+z.w<cam.x-20||z.x>cam.x+canvas.width+20||z.y+z.h<cam.y-20||z.y>cam.y+canvas.height+20)continue;ctx.save();ctx.globalAlpha=.09;ctx.fillStyle=z.color||'#668080';ctx.fillRect(z.x,z.y,z.w,z.h);ctx.globalAlpha=.18;ctx.strokeStyle=z.color||'#668080';ctx.lineWidth=2;ctx.strokeRect(z.x,z.y,z.w,z.h);ctx.globalAlpha=.38;ctx.font='bold 30px monospace';ctx.fillStyle=z.color||'#b6c4c4';ctx.fillText(z.name,z.x+24,z.y+50);ctx.restore()}}
function drawExtracts(cam){for(const e of snap.extracts){if(!onScreen(e.x,e.y,cam,300))continue;ctx.fillStyle='rgba(69,156,96,.11)';ctx.fillRect(e.x,e.y,e.w,e.h);ctx.strokeStyle='rgba(92,205,126,.38)';ctx.strokeRect(e.x,e.y,e.w,e.h);ctx.fillStyle='rgba(145,216,166,.55)';ctx.font='11px monospace';ctx.fillText('EXTRACT',e.x+7,e.y+17)}}
function obstacleColor(k){const p=snap.map?.palette||{};return k==='container'?(p.container||'#87573b'):k==='vehicle'||k==='truck'?(p.vehicle||'#415763'):k==='tank'?(p.tank||'#58634a'):k==='shelf'?(p.shelf||'#6e5a39'):k==='machine'?(p.machine||'#3f6061'):k==='desk'?(p.desk||'#594a43'):k==='barricade'||k==='cratewall'?(p.barricade||'#75603e'):k==='pipe'?(p.pipe||'#526a62'):k==='water'?(p.water||'#25505e'):(p.wall||'#354044')}
function drawObstacles(cam){for(const o of snap.obstacles){if(o.x+o.w<cam.x-40||o.x>cam.x+canvas.width+40||o.y+o.h<cam.y-40||o.y>cam.y+canvas.height+40||!rectInVision(o))continue;ctx.fillStyle=obstacleColor(o.kind);ctx.fillRect(o.x,o.y,o.w,o.h);ctx.fillStyle='rgba(255,255,255,.055)';ctx.fillRect(o.x,o.y,o.w,3);ctx.strokeStyle='rgba(0,0,0,.42)';ctx.strokeRect(o.x,o.y,o.w,o.h)}}
function drawDoors(cam){for(const d of snap.doors||[]){if(!rectInVision(d))continue;ctx.save();const cx=d.x+d.w/2,cy=d.y+d.h/2;ctx.translate(cx,cy);if(d.open){ctx.strokeStyle=snap.map?.palette?.door||'#92785e';ctx.lineWidth=5;ctx.beginPath();if(d.w>d.h){ctx.moveTo(-d.w/2,0);ctx.lineTo(-d.w/2,-Math.min(72,d.w));}else{ctx.moveTo(0,-d.h/2);ctx.lineTo(Math.min(72,d.h),-d.h/2);}ctx.stroke()}else{ctx.fillStyle=snap.map?.palette?.door||'#6f5945';ctx.fillRect(-d.w/2,-d.h/2,d.w,d.h);ctx.strokeStyle='#b29269';ctx.strokeRect(-d.w/2,-d.h/2,d.w,d.h)}ctx.restore()}}
function drawCrates(cam){for(const c of snap.crates){if(!onScreen(c.x,c.y,cam)||!pointInVision(c.x,c.y))continue;ctx.fillStyle=c.opened?'#403b31':'#79633b';ctx.fillRect(c.x-16,c.y-12,32,24);ctx.strokeStyle=c.empty?'#4d4d47':'#b39454';ctx.strokeRect(c.x-16,c.y-12,32,24);if(!c.opened){ctx.fillStyle='#c8a961';ctx.fillRect(c.x-10,c.y-3,20,3)}}}
function drawCorpses(cam){for(const c of snap.corpses){if(!onScreen(c.x,c.y,cam)||!pointInVision(c.x,c.y))continue;ctx.fillStyle='#302928';ctx.beginPath();ctx.ellipse(c.x,c.y,19,10,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#685a55';ctx.stroke()}}
function actorColor(a){if(a.id===snap.playerId)return'#76b8cf';if(a.kind==='player')return'#c87561';return a.kind==='pmc'?'#aba89a':'#948b6d'}
function drawActors(cam){for(const a of snap.actors){const r=renderActors.get(a.id),x=r?.x??a.x,y=r?.y??a.y,ang=r?.angle??a.angle;if(a.dead||!onScreen(x,y,cam))continue;const self=a.id===snap.playerId,moving=a.moving||(self&&(keys.has('w')||keys.has('a')||keys.has('s')||keys.has('d'))),sprinting=a.sprinting||(self&&moving&&keys.has('shift')),moveAng=a.moveAngle??ang,hit=actorHitFlash.get(a.id);if(sprinting&&moving){ctx.save();ctx.strokeStyle=self?'rgba(120,220,255,.32)':'rgba(230,190,150,.24)';ctx.lineWidth=2;for(let i=-1;i<=1;i++){const side=moveAng+Math.PI/2,ox=Math.cos(side)*i*7,oy=Math.sin(side)*i*7;ctx.beginPath();ctx.moveTo(x+ox-Math.cos(moveAng)*10,y+oy-Math.sin(moveAng)*10);ctx.lineTo(x+ox-Math.cos(moveAng)*30,y+oy-Math.sin(moveAng)*30);ctx.stroke()}ctx.restore()}ctx.save();ctx.translate(x,y);ctx.rotate(ang);ctx.fillStyle='rgba(0,0,0,.45)';ctx.beginPath();ctx.ellipse(0,10,14,6,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=hit?'#e34d4d':actorColor(a);ctx.fillRect(-9,-10,18,21);ctx.fillStyle=hit?'#7f2323':'#181d20';ctx.fillRect(-6,-15,12,8);ctx.strokeStyle=hit?'#ffb0a6':'#c9ced0';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(5,0);ctx.lineTo(25,0);ctx.stroke();ctx.restore();if(hit){ctx.strokeStyle='rgba(255,72,64,.9)';ctx.lineWidth=2.5;ctx.beginPath();ctx.arc(x,y,21,0,Math.PI*2);ctx.stroke()}if(self){ctx.strokeStyle='rgba(115,192,217,.8)';ctx.beginPath();ctx.arc(x,y,18,0,Math.PI*2);ctx.stroke()}}}
function drawBullets(cam){const age=Math.min(.055,Math.max(0,(performance.now()-lastSnapshotAt)/1000));for(const b of snap.bullets){const x=b.x+b.vx*age,y=b.y+b.vy*age;if(!onScreen(x,y,cam))continue;const a=Math.atan2(b.vy,b.vx),self=b.owner===snap.playerId;ctx.save();ctx.strokeStyle=self?'rgba(205,246,255,.99)':'rgba(255,164,92,.99)';ctx.lineWidth=self?3.4:3;ctx.shadowColor=self?'rgba(110,220,255,.98)':'rgba(255,104,48,.95)';ctx.shadowBlur=TOUCH_MODE?0:8;ctx.beginPath();ctx.moveTo(x-Math.cos(a)*30,y-Math.sin(a)*30);ctx.lineTo(x,y);ctx.stroke();ctx.restore()}}
function drawGrenades(cam){for(const g of snap.grenades){if(!onScreen(g.x,g.y,cam))continue;ctx.fillStyle='#59605c';ctx.beginPath();ctx.arc(g.x,g.y,6,0,Math.PI*2);ctx.fill();ctx.fillStyle=g.fuse<.7?'#e06757':'#9ca59e';ctx.fillRect(g.x-1,g.y-9,2,4)}}
function drawFxWorld(cam){for(const f of fx){if(!onScreen(f.x,f.y,cam))continue;const a=Math.max(0,f.t/f.max);ctx.globalAlpha=a;if(f.kind==='muzzle'){ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.angle||0);ctx.fillStyle=f.self?'#dff9ff':'#ff9857';ctx.shadowColor=f.self?'#7fdfff':'#ff5f32';ctx.shadowBlur=TOUCH_MODE?0:(f.self?18:13);const len=(f.self?34:27)*(1+.35*(1-a));ctx.beginPath();ctx.moveTo(len,0);ctx.lineTo(-5,-8);ctx.lineTo(2,0);ctx.lineTo(-5,8);ctx.closePath();ctx.fill();ctx.beginPath();ctx.arc(0,0,f.self?9:7,0,Math.PI*2);ctx.fill();ctx.restore()}else if(f.kind==='impact'){ctx.fillStyle='#e5d9b4';for(let i=0;i<4;i++)ctx.fillRect(f.x+(Math.random()-.5)*10,f.y+(Math.random()-.5)*10,2,2)}else if(f.kind==='spark'){ctx.fillStyle='#f1b75e';ctx.fillRect(f.x-2,f.y-2,4,4)}else if(f.kind==='casing'){ctx.fillStyle='#c5a258';ctx.fillRect(f.x,f.y,4,2)}else if(f.kind==='damage'){ctx.fillStyle='#ff6b61';ctx.font='bold 13px monospace';ctx.textAlign='center';ctx.fillText(f.text||'',f.x,f.y-(1-a)*18);ctx.textAlign='start'}ctx.globalAlpha=1}}
function drawDarkness(cam){
 if(!snap?.player)return;
 const p=visualPlayer()||snap.player,scale=TOUCH_MODE?.30:.4,sx=(p.x-cam.x)*scale,sy=(p.y-cam.y)*scale,level=p.visionLevel;
 const near=(190+level*34)*scale,far=(190+level*34+430+level*58)*scale,half=1.05;
 const fog=drawDarkness._fog||(drawDarkness._fog=document.createElement('canvas')),fw=Math.ceil(canvas.width*scale),fh=Math.ceil(canvas.height*scale);
 if(fog.width!==fw||fog.height!==fh){fog.width=fw;fog.height=fh}
 const fctx=fog.getContext('2d');fctx.setTransform(1,0,0,1,0,0);fctx.clearRect(0,0,fw,fh);fctx.globalCompositeOperation='source-over';fctx.fillStyle='rgba(2,5,8,.34)';fctx.fillRect(0,0,fw,fh);fctx.globalCompositeOperation='destination-out';
 let g=fctx.createRadialGradient(sx,sy,8,sx,sy,near);g.addColorStop(0,'rgba(0,0,0,.82)');g.addColorStop(.58,'rgba(0,0,0,.66)');g.addColorStop(1,'rgba(0,0,0,0)');fctx.fillStyle=g;fctx.beginPath();fctx.arc(sx,sy,near,0,Math.PI*2);fctx.fill();
 fctx.save();fctx.translate(sx,sy);fctx.rotate(p.angle);const cone=fctx.createRadialGradient(0,0,near*.18,0,0,far);cone.addColorStop(0,'rgba(0,0,0,.98)');cone.addColorStop(.62,'rgba(0,0,0,.94)');cone.addColorStop(.86,'rgba(0,0,0,.66)');cone.addColorStop(1,'rgba(0,0,0,0)');fctx.fillStyle=cone;fctx.beginPath();fctx.moveTo(0,0);fctx.arc(0,0,far,-half,half);fctx.closePath();fctx.fill();fctx.restore();fctx.globalCompositeOperation='source-over';ctx.drawImage(fog,0,0,fw,fh,0,0,canvas.width,canvas.height);
}
function drawSprintOverlay(){if(!snap?.player)return;const moving=keys.has('w')||keys.has('a')||keys.has('s')||keys.has('d');if(!(keys.has('shift')&&moving))return;const cx=canvas.width/2,cy=canvas.height/2,t=performance.now()*.02;ctx.save();ctx.strokeStyle='rgba(155,225,255,.13)';ctx.lineWidth=1.5;for(let i=0;i<12;i++){const a=i/12*Math.PI*2+t*.015,r=250+(i%3)*38,x1=cx+Math.cos(a)*r,y1=cy+Math.sin(a)*r,x2=cx+Math.cos(a)*(r+26),y2=cy+Math.sin(a)*(r+26);ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}ctx.restore()}
function drawDamageOverlay(){if(hurtFlashT<=0)return;const a=Math.min(.28,hurtFlashT/.24*.28),g=ctx.createRadialGradient(canvas.width/2,canvas.height/2,120,canvas.width/2,canvas.height/2,Math.max(canvas.width,canvas.height)*.68);g.addColorStop(0,'rgba(150,0,0,0)');g.addColorStop(1,`rgba(210,24,20,${a})`);ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height)}
function drawSoundIndicators(){const cx=canvas.width/2,cy=canvas.height/2,r=Math.min(canvas.width,canvas.height)*.43;for(const s of soundMarks){const fade=Math.min(1,(s.t/s.max)*1.7),x=cx+Math.cos(s.angle)*r,y=cy+Math.sin(s.angle)*r,baseScale=s.intensity==='near'?1.18:s.intensity==='far'?0.82:1,scale=baseScale*(s.loud?1.35:1);ctx.save();ctx.translate(x,y);ctx.rotate(s.angle);ctx.globalAlpha=fade;if(s.kind==='footstep'){ctx.strokeStyle='#e9edf0';ctx.lineWidth=3;for(const off of [-6,6]){ctx.beginPath();ctx.arc(0,off,5*scale,-.9,.9);ctx.stroke()}ctx.fillStyle='#e9edf0';ctx.font='bold 9px monospace';ctx.fillText('STEP',-12,18)}else if(s.kind==='gunshot'){ctx.fillStyle='#ffb36b';ctx.beginPath();ctx.moveTo(16*scale,0);ctx.lineTo(-9,-9);ctx.lineTo(-3,0);ctx.lineTo(-9,9);ctx.closePath();ctx.fill();ctx.strokeStyle='#ffcf9d';ctx.lineWidth=2;for(const yy of [-11,11]){ctx.beginPath();ctx.moveTo(-2,yy);ctx.lineTo(7,yy*1.25);ctx.stroke()}}else if(s.kind==='explosion'){ctx.strokeStyle='#ff7b61';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,12*scale,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(-18,0);ctx.lineTo(18,0);ctx.moveTo(0,-18);ctx.lineTo(0,18);ctx.stroke()}else{ctx.fillStyle='#d5d9d8';ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(-8,-8);ctx.lineTo(-3,0);ctx.lineTo(-8,8);ctx.closePath();ctx.fill()}ctx.restore()}ctx.globalAlpha=1}
function drawCrosshair(){if(!session)return;let cx=mouse.x,cy=mouse.y;if(TOUCH_MODE&&snap?.player){const cam=camera(),p=visualPlayer()||snap.player;cx=p.x-cam.x+touchAim.x*150;cy=p.y-cam.y+touchAim.y*150}ctx.save();ctx.translate(cx,cy);ctx.strokeStyle='rgba(225,242,247,.92)';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,0,7,0,Math.PI*2);ctx.moveTo(-13,0);ctx.lineTo(-5,0);ctx.moveTo(13,0);ctx.lineTo(5,0);ctx.moveTo(0,-13);ctx.lineTo(0,-5);ctx.moveTo(0,13);ctx.lineTo(0,5);ctx.stroke();ctx.restore()}

function updateInput(){if(!session||!snap?.player)return;let x=touchMove.x,y=touchMove.y;if(keys.has('w'))y--;if(keys.has('s'))y++;if(keys.has('a'))x--;if(keys.has('d'))x++;let aimX=touchAim.x,aimY=touchAim.y;if(!TOUCH_MODE){const cam=camera(),wx=mouse.x+cam.x,wy=mouse.y+cam.y,dx=wx-snap.player.x,dy=wy-snap.player.y,l=Math.hypot(dx,dy)||1;aimX=dx/l;aimY=dy/l}input={...input,seq:input.seq+1,moveX:x,moveY:y,aimX,aimY,sprint:keys.has('shift')||touchMove.sprint,interact:keys.has('e')||touchInteract,reload:keys.has('r')||touchReload};session.sendInput(input);touchReload=false;input.reload=false}
setInterval(updateInput,1000/30);
canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect(),sx=canvas.width/r.width,sy=canvas.height/r.height;if(document.pointerLockElement===canvas){mouse.x=Math.max(8,Math.min(canvas.width-8,mouse.x+e.movementX*sx));mouse.y=Math.max(8,Math.min(canvas.height-8,mouse.y+e.movementY*sy))}else{mouse.x=Math.max(8,Math.min(canvas.width-8,(e.clientX-r.left)*sx));mouse.y=Math.max(8,Math.min(canvas.height-8,(e.clientY-r.top)*sy))}});canvas.addEventListener('mousedown',e=>{if(TOUCH_MODE)return;if(e.button===0){ensureAudio();if(session&&!snap?.openContainer&&document.pointerLockElement!==canvas&&canvas.requestPointerLock){canvas.requestPointerLock();toast('마우스 조준 고정 · ESC로 해제');return}input.shoot=true}});window.addEventListener('mouseup',e=>{if(e.button===0)input.shoot=false});document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==canvas)input.shoot=false});canvas.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','shift','e','r','g','h','1','2'].includes(k))e.preventDefault();keys.add(k);if(!session||e.repeat)return;if(k==='g')session.sendAction({type:ACTIONS.GRENADE});else if(k==='h')session.sendAction({type:ACTIONS.USE_MED});else if(k==='1')session.sendAction({type:ACTIONS.SWAP_WEAPON,slot:'primary'});else if(k==='2')session.sendAction({type:ACTIONS.SWAP_WEAPON,slot:'secondary'})});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function setupMobileControls(){
 const root=$('#mobileControls');if(!TOUCH_MODE||!root)return;root.setAttribute('aria-hidden','false');
 const bindStick=(el,knob,onMove,onEnd)=>{if(!el||!knob)return;let pointerId=null;const update=e=>{const r=el.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=Math.min(r.width,r.height)*.34;let dx=e.clientX-cx,dy=e.clientY-cy,d=Math.hypot(dx,dy),mag=Math.min(1,d/max);if(d>max){dx=dx/d*max;dy=dy/d*max;d=max}knob.style.transform='translate(calc(-50% + '+dx.toFixed(1)+'px),calc(-50% + '+dy.toFixed(1)+'px))';onMove(d>0?dx/d:0,d>0?dy/d:0,mag)};const end=e=>{if(pointerId!==null&&e.pointerId!==pointerId)return;pointerId=null;knob.style.transform='translate(-50%,-50%)';onEnd?.()};el.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();pointerId=e.pointerId;try{el.setPointerCapture(pointerId)}catch{}update(e)});el.addEventListener('pointermove',e=>{if(e.pointerId!==pointerId)return;e.preventDefault();update(e)});el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('lostpointercapture',e=>{if(pointerId===e.pointerId)end(e)})};
 bindStick($('#mobileMoveStick'),$('#mobileMoveKnob'),(x,y,mag)=>{if(mag<.14){touchMove={x:0,y:0,sprint:false};return}touchMove={x,y,sprint:mag>.82}},()=>{touchMove={x:0,y:0,sprint:false}});
 bindStick($('#mobileAimStick'),$('#mobileAimKnob'),(x,y,mag)=>{if(mag>.10){touchAim={x,y}}input.shoot=mag>.72},()=>{input.shoot=false});
 const press=(name,fn)=>{const b=root.querySelector('[data-mobile="'+name+'"]');if(!b)return;b.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();fn(e)})};
 press('reload',()=>{touchReload=true});press('grenade',()=>session?.sendAction({type:ACTIONS.GRENADE}));press('heal',()=>session?.sendAction({type:ACTIONS.USE_MED}));press('primary',()=>session?.sendAction({type:ACTIONS.SWAP_WEAPON,slot:'primary'}));press('secondary',()=>session?.sendAction({type:ACTIONS.SWAP_WEAPON,slot:'secondary'}));press('bag',()=>$('#raid').classList.toggle('mobileBagOpen'));
 const interact=root.querySelector('[data-mobile="interact"]');if(interact){const stop=e=>{e?.preventDefault?.();touchInteract=false};interact.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();touchInteract=true;try{interact.setPointerCapture(e.pointerId)}catch{}});interact.addEventListener('pointerup',stop);interact.addEventListener('pointercancel',stop);interact.addEventListener('lostpointercapture',stop)}
 $('#mobileBagClose')?.addEventListener('pointerdown',e=>{e.preventDefault();$('#raid').classList.remove('mobileBagOpen')});
 window.addEventListener('blur',()=>{touchMove={x:0,y:0,sprint:false};touchInteract=false;touchReload=false;input.shoot=false});
}
setupMobileControls();
ensureBasicPistol();setupRealtime();renderLobby();renderRoomStatus();requestAnimationFrame(draw);
