import {experimental_upgradeWebSocket} from '@vercel/functions';
import {createWorld,stepWorld,setPlayerInput,applyAction,buildSnapshot,drainEvents,addHumanPlayer,restoreHumanPlayer,removeHumanPlayer,reconcileFillerAI} from '../src/sim.js';
import {emptyInput} from '../src/protocol.js';

const CYCLE_MS=10*60*1000,CAPACITY=8,ENTRY_LOCK_MS=60_000,FIXED=1/30,SNAPSHOT_MS=50,STATUS_MS=1000,RECONNECT_GRACE_MS=150_000;
const shared=globalThis.__DEAD_DROP_RT_V340__||(globalThis.__DEAD_DROP_RT_V340__={rooms:new Map(),sockets:new Set(),socketMeta:new WeakMap(),resumes:new Map(),timer:null,lastTick:Date.now(),lastStatus:0});
const sm=ws=>{let d=shared.socketMeta.get(ws);if(!d){d={roomKey:null,playerId:null,resumeToken:null,fullSent:false};shared.socketMeta.set(ws,d)}return d};
const safeSend=(ws,msg)=>{try{ws.send(JSON.stringify(msg))}catch{}};
const roomKey=(now=Date.now())=>Math.floor(now/CYCLE_MS),roomId=k=>`IND-${String(k).slice(-6)}`;
function createRoom(key){const start=key*CYCLE_MS,end=start+CYCLE_MS,mapIndex=((key%3)+3)%3,world=createWorld({players:[],aiCount:CAPACITY,mapIndex,coverSeed:key});world.timeLeft=Math.max(0,(end-Date.now())/1000);const r={key,id:roomId(key),start,end,world,clients:new Set(),byPlayer:new Map(),nextAiFill:start+60_000,lastSnapshot:0,ended:false};shared.rooms.set(key,r);return r}
function getRoom(key){return shared.rooms.get(key)||createRoom(key)}
function currentRoom(now=Date.now()){return getRoom(roomKey(now))}
function liveHumans(r){return r.world.actors.filter(a=>a.kind==='player'&&!a.dead&&!r.world.results[a.id]).length}
function liveAI(r){return r.world.actors.filter(a=>a.kind!=='player'&&!a.dead).length}
function statusFor(r,now=Date.now()){const humans=liveHumans(r),remainingMs=Math.max(0,r.end-now),entryClosed=remainingMs<=ENTRY_LOCK_MS;return{roomId:r.id,roomKey:r.key,humans,ai:liveAI(r),capacity:CAPACITY,endsAt:r.end,remainingMs,entryClosed,mapId:r.world.map?.id,mapName:r.world.map?.name,mapTrait:r.world.map?.trait||'',joinable:humans<CAPACITY&&!entryClosed}}
function statusData(now=Date.now()){return statusFor(currentRoom(now),now)}
function broadcastStatus(now=Date.now()){const data=statusData(now);for(const ws of shared.sockets)safeSend(ws,{type:'status',data})}
function removePlayerFromRoom(r,id,{drop=true}={}){if(!r||!id)return;const hadResult=!!r.world.results[id];removeHumanPlayer(r.world,id,{drop:drop&&!hadResult});r.byPlayer.delete(id);for(const [token,rec] of shared.resumes)if(rec.roomKey===r.key&&rec.playerId===id)shared.resumes.delete(token)}
function cleanupPlayer(ws,{drop=true}={}){const d=sm(ws),r=shared.rooms.get(d.roomKey),id=d.playerId;if(r&&id){removePlayerFromRoom(r,id,{drop});r.clients.delete(ws)}if(d.resumeToken)shared.resumes.delete(d.resumeToken);d.roomKey=null;d.playerId=null;d.resumeToken=null;d.fullSent=false}
function markDisconnected(ws){const d=sm(ws),r=shared.rooms.get(d.roomKey),id=d.playerId;if(!r||!id)return;setPlayerInput(r.world,id,emptyInput());r.clients.delete(ws);r.byPlayer.delete(id);const rec=d.resumeToken?shared.resumes.get(d.resumeToken):null;if(rec&&rec.playerId===id&&rec.roomKey===r.key){rec.expiresAt=Date.now()+RECONNECT_GRACE_MS;shared.resumes.set(d.resumeToken,rec)}else removePlayerFromRoom(r,id,{drop:true});d.roomKey=null;d.playerId=null;d.resumeToken=null;d.fullSent=false}
function attachSocketToPlayer(ws,r,id,token,resumed){const d=sm(ws);const old=r.byPlayer.get(id);if(old&&old!==ws){const od=sm(old);od.roomKey=null;od.playerId=null;od.resumeToken=null;od.fullSent=false;try{old.close()}catch{}}const nextToken=crypto.randomUUID();if(token)shared.resumes.delete(token);shared.resumes.set(nextToken,{roomKey:r.key,playerId:id,expiresAt:0});d.roomKey=r.key;d.playerId=id;d.resumeToken=nextToken;d.fullSent=false;r.byPlayer.set(id,ws);r.clients.add(ws);safeSend(ws,{type:'joined',data:{playerId:id,roomId:r.id,roomKey:r.key,endsAt:r.end,resumeToken:nextToken,reconnectGraceMs:RECONNECT_GRACE_MS,resumed}});const snap=buildSnapshot(r.world,id);if(snap){snap.room=statusFor(r);safeSend(ws,{type:'snapshot',full:true,data:snap});d.fullSent=true}}
function joinCurrent(ws,config={}){const d=sm(ws);if(d.playerId)return;const r=currentRoom(),humans=liveHumans(r),remainingMs=Math.max(0,r.end-Date.now());if(humans>=CAPACITY||remainingMs<=ENTRY_LOCK_MS)return safeSend(ws,{type:'join_denied',reason:humans>=CAPACITY?'현재 방이 가득 찼습니다.':'현재 RAID는 종료 1분 전이라 신규 참가가 마감되었습니다.'});reconcileFillerAI(r.world,Math.max(0,CAPACITY-(humans+1)),{onlyRemove:true});const id=addHumanPlayer(r.world,{...config,name:(config.name||'PLAYER').slice(0,18)});attachSocketToPlayer(ws,r,id,null,false)}
function resume(ws,data={}){const token=String(data.token||''),now=Date.now();let rec=shared.resumes.get(token);if(rec&&rec.expiresAt>0&&now>rec.expiresAt){const r=shared.rooms.get(rec.roomKey);if(r)removePlayerFromRoom(r,rec.playerId,{drop:true});shared.resumes.delete(token);rec=null}if(rec){const r=shared.rooms.get(rec.roomKey),actor=r?.world.actors.find(a=>a.id===rec.playerId);if(r&&actor)return attachSocketToPlayer(ws,r,rec.playerId,token,true);shared.resumes.delete(token)}
 const key=Number(data.roomKey),savedAt=Number(data.savedAt)||0,recovery=data.recovery,current=roomKey(now);if(!Number.isFinite(key)||key<current-1||key>current||!recovery||now-savedAt>RECONNECT_GRACE_MS+15_000)return safeSend(ws,{type:'resume_denied',reason:'복귀 가능한 RAID 세션이 없거나 재접속 시간이 초과되었습니다.'});const r=getRoom(key);if(now>r.end+RECONNECT_GRACE_MS)return safeSend(ws,{type:'resume_denied',reason:'해당 RAID가 이미 종료되었습니다.'});const humans=liveHumans(r);if(humans>=CAPACITY)return safeSend(ws,{type:'resume_denied',reason:'복구할 방의 플레이어 슬롯이 가득 찼습니다.'});reconcileFillerAI(r.world,Math.max(0,CAPACITY-(humans+1)),{onlyRemove:true});const id=restoreHumanPlayer(r.world,recovery);attachSocketToPlayer(ws,r,id,token,true)}
function handleMessage(ws,raw){let m;try{m=JSON.parse(raw.toString())}catch{return}if(m.type==='watch')return safeSend(ws,{type:'status',data:statusData()});if(m.type==='join')return joinCurrent(ws,m.data||{});if(m.type==='resume')return resume(ws,m.data||{});if(m.type==='leave'){cleanupPlayer(ws,{drop:true});return safeSend(ws,{type:'left'})}const d=sm(ws),r=shared.rooms.get(d.roomKey),id=d.playerId;if(!r||!id)return;if(m.type==='input')setPlayerInput(r.world,id,m.data||{});else if(m.type==='action')applyAction(r.world,id,m.data||{})}
function sendEvents(r){for(const e of drainEvents(r.world)){if(e.recipient){const ws=r.byPlayer.get(e.recipient);if(ws)safeSend(ws,{type:'event',data:e})}else for(const ws of r.clients)safeSend(ws,{type:'event',data:e})}}
function sendSnapshots(r,now){if(now-r.lastSnapshot<SNAPSHOT_MS)return;r.lastSnapshot=now;const st=statusFor(r,now);for(const [id,ws] of r.byPlayer){const snap=buildSnapshot(r.world,id);if(!snap)continue;snap.room=st;const d=sm(ws),full=!d.fullSent;if(!full){delete snap.obstacles;delete snap.zones;delete snap.extracts;delete snap.worldW;delete snap.worldH}safeSend(ws,{type:'snapshot',full,data:snap});d.fullSent=true}}
function cleanupExpiredResumes(now){for(const [token,rec] of [...shared.resumes]){if(!(rec.expiresAt>0)||now<rec.expiresAt)continue;const r=shared.rooms.get(rec.roomKey);if(r&&!r.byPlayer.has(rec.playerId))removePlayerFromRoom(r,rec.playerId,{drop:true});shared.resumes.delete(token)}}
function tick(){const now=Date.now(),elapsed=Math.min(.1,Math.max(0,(now-shared.lastTick)/1000));shared.lastTick=now;currentRoom(now);cleanupExpiredResumes(now);for(const [key,r] of shared.rooms){const remaining=Math.max(0,(r.end-now)/1000);r.world.timeLeft=remaining;if(remaining>0){r._acc=(r._acc||0)+elapsed;let guard=0;while(r._acc>=FIXED&&guard++<4){stepWorld(r.world,FIXED);r._acc-=FIXED;r.world.timeLeft=Math.max(0,(r.end-Date.now())/1000)}}else if(!r.ended){r.world.timeLeft=0;stepWorld(r.world,.001);r.ended=true}if(remaining>0&&now>=r.nextAiFill){reconcileFillerAI(r.world,Math.max(0,CAPACITY-liveHumans(r)));while(r.nextAiFill<=now)r.nextAiFill+=60_000}sendEvents(r);sendSnapshots(r,now);const hasResume=[...shared.resumes.values()].some(x=>x.roomKey===key);if(now>r.end+RECONNECT_GRACE_MS&&r.byPlayer.size===0&&!hasResume)shared.rooms.delete(key)}if(now-shared.lastStatus>=STATUS_MS){shared.lastStatus=now;broadcastStatus(now)}}
if(!shared.timer)shared.timer=setInterval(tick,16);
function upgrade(){return experimental_upgradeWebSocket(ws=>{sm(ws);shared.sockets.add(ws);safeSend(ws,{type:'hello',data:{protocol:2,serverTime:Date.now(),reconnectGraceMs:RECONNECT_GRACE_MS}});safeSend(ws,{type:'status',data:statusData()});ws.on('message',data=>handleMessage(ws,data));ws.on('close',()=>{markDisconnected(ws);shared.sockets.delete(ws)});ws.on('error',()=>{})},{maxPayload:256*1024})}
export async function GET(){return upgrade()}
export default {fetch(request){if(request.headers.get('upgrade')?.toLowerCase()==='websocket')return upgrade();return Response.json({ok:false,message:'WebSocket upgrade required',room:statusData()},{status:426})}};
