import {experimental_upgradeWebSocket} from '@vercel/functions';
import {
  createWorld,stepWorld,setPlayerInput,applyAction,buildSnapshot,drainEvents,
  addHumanPlayer,removeHumanPlayer,reconcileFillerAI
} from '../src/sim.js';

const CYCLE_MS=10*60*1000,CAPACITY=8,ENTRY_LOCK_MS=60_000,FIXED=1/30,SNAPSHOT_MS=50,STATUS_MS=1000;
const shared=globalThis.__DEAD_DROP_RT__||(globalThis.__DEAD_DROP_RT__={rooms:new Map(),sockets:new Set(),socketMeta:new WeakMap(),timer:null,lastTick:Date.now(),lastStatus:0});
const sm=ws=>{let d=shared.socketMeta.get(ws);if(!d){d={roomKey:null,playerId:null,fullSent:false};shared.socketMeta.set(ws,d)}return d};
const safeSend=(ws,msg)=>{try{ws.send(JSON.stringify(msg))}catch{}};
const roomKey=(now=Date.now())=>Math.floor(now/CYCLE_MS),roomId=k=>`IND-${String(k).slice(-6)}`;
function createRoom(key){const start=key*CYCLE_MS,end=start+CYCLE_MS,mapIndex=((key%3)+3)%3,world=createWorld({players:[],aiCount:CAPACITY,mapIndex});world.timeLeft=Math.max(0,(end-Date.now())/1000);const r={key,id:roomId(key),start,end,world,clients:new Set(),byPlayer:new Map(),nextAiFill:start+60_000,lastSnapshot:0,ended:false};shared.rooms.set(key,r);return r}
function currentRoom(now=Date.now()){const k=roomKey(now);return shared.rooms.get(k)||createRoom(k)}
function liveHumans(r){let n=0;for(const id of r.byPlayer.keys()){const a=r.world.actors.find(x=>x.id===id);if(a&&!a.dead&&!r.world.results[id])n++}return n}
function liveAI(r){return r.world.actors.filter(a=>a.kind!=='player'&&!a.dead).length}
function statusData(now=Date.now()){const r=currentRoom(now),humans=liveHumans(r),remainingMs=Math.max(0,r.end-now),entryClosed=remainingMs<=ENTRY_LOCK_MS;return{roomId:r.id,roomKey:r.key,humans,ai:liveAI(r),capacity:CAPACITY,endsAt:r.end,remainingMs,entryClosed,mapId:r.world.map?.id,mapName:r.world.map?.name,joinable:humans<CAPACITY&&!entryClosed}}
function broadcastStatus(now=Date.now()){const data=statusData(now);for(const ws of shared.sockets)safeSend(ws,{type:'status',data})}
function cleanupPlayer(ws,{drop=true}={}){const d=sm(ws),r=shared.rooms.get(d.roomKey),id=d.playerId;if(r&&id){const hadResult=!!r.world.results[id];removeHumanPlayer(r.world,id,{drop:drop&&!hadResult});r.byPlayer.delete(id);r.clients.delete(ws)}d.roomKey=null;d.playerId=null;d.fullSent=false}
function joinCurrent(ws,config={}){const d=sm(ws);if(d.playerId)return;const r=currentRoom(),humans=liveHumans(r),remainingMs=Math.max(0,r.end-Date.now());if(humans>=CAPACITY||remainingMs<=ENTRY_LOCK_MS)return safeSend(ws,{type:'join_denied',reason:humans>=CAPACITY?'현재 방이 가득 찼습니다.':'현재 RAID는 종료 1분 전이라 신규 참가가 마감되었습니다.'});reconcileFillerAI(r.world,Math.max(0,CAPACITY-(humans+1)),{onlyRemove:true});const id=addHumanPlayer(r.world,{...config,name:(config.name||'PLAYER').slice(0,18)});d.roomKey=r.key;d.playerId=id;d.fullSent=false;r.byPlayer.set(id,ws);r.clients.add(ws);safeSend(ws,{type:'joined',data:{playerId:id,roomId:r.id,endsAt:r.end}});const snap=buildSnapshot(r.world,id);snap.room=statusData();safeSend(ws,{type:'snapshot',full:true,data:snap});d.fullSent=true}
function handleMessage(ws,raw){let m;try{m=JSON.parse(raw.toString())}catch{return}if(m.type==='watch')return safeSend(ws,{type:'status',data:statusData()});if(m.type==='join')return joinCurrent(ws,m.data||{});if(m.type==='leave'){cleanupPlayer(ws,{drop:true});return safeSend(ws,{type:'left'})}const d=sm(ws),r=shared.rooms.get(d.roomKey),id=d.playerId;if(!r||!id)return;if(m.type==='input')setPlayerInput(r.world,id,m.data||{});else if(m.type==='action')applyAction(r.world,id,m.data||{})}
function sendEvents(r){for(const e of drainEvents(r.world)){if(e.recipient){const ws=r.byPlayer.get(e.recipient);if(ws)safeSend(ws,{type:'event',data:e})}else for(const ws of r.clients)safeSend(ws,{type:'event',data:e})}}
function sendSnapshots(r,now){if(now-r.lastSnapshot<SNAPSHOT_MS)return;r.lastSnapshot=now;const humans=liveHumans(r),remainingMs=Math.max(0,r.end-now),entryClosed=remainingMs<=ENTRY_LOCK_MS,st={roomId:r.id,roomKey:r.key,humans,ai:liveAI(r),capacity:CAPACITY,endsAt:r.end,remainingMs,entryClosed,mapId:r.world.map?.id,mapName:r.world.map?.name,joinable:humans<CAPACITY&&!entryClosed};for(const [id,ws] of r.byPlayer){const snap=buildSnapshot(r.world,id);if(!snap)continue;snap.room=st;const d=sm(ws),full=!d.fullSent;if(!full){delete snap.obstacles;delete snap.zones;delete snap.extracts;delete snap.worldW;delete snap.worldH}safeSend(ws,{type:'snapshot',full,data:snap});d.fullSent=true}}
function tick(){const now=Date.now(),elapsed=Math.min(.1,Math.max(0,(now-shared.lastTick)/1000));shared.lastTick=now;currentRoom(now);for(const [key,r] of shared.rooms){const remaining=Math.max(0,(r.end-now)/1000);r.world.timeLeft=remaining;if(remaining>0){r._acc=(r._acc||0)+elapsed;let guard=0;while(r._acc>=FIXED&&guard++<4){stepWorld(r.world,FIXED);r._acc-=FIXED;r.world.timeLeft=Math.max(0,(r.end-Date.now())/1000)}}else if(!r.ended){r.world.timeLeft=0;stepWorld(r.world,.001);r.ended=true}if(remaining>0&&now>=r.nextAiFill){reconcileFillerAI(r.world,Math.max(0,CAPACITY-liveHumans(r)));while(r.nextAiFill<=now)r.nextAiFill+=60_000}sendEvents(r);sendSnapshots(r,now);if(now>r.end+30_000&&r.byPlayer.size===0)shared.rooms.delete(key)}if(now-shared.lastStatus>=STATUS_MS){shared.lastStatus=now;broadcastStatus(now)}}
if(!shared.timer)shared.timer=setInterval(tick,16);

function upgrade(){return experimental_upgradeWebSocket(ws=>{sm(ws);shared.sockets.add(ws);safeSend(ws,{type:'hello',data:{protocol:1,serverTime:Date.now()}});safeSend(ws,{type:'status',data:statusData()});ws.on('message',data=>handleMessage(ws,data));ws.on('close',()=>{cleanupPlayer(ws,{drop:true});shared.sockets.delete(ws)});ws.on('error',()=>{})},{maxPayload:256*1024})}
export async function GET(){return upgrade()}
export default {fetch(request){if(request.headers.get('upgrade')?.toLowerCase()==='websocket')return upgrade();return Response.json({ok:false,message:'WebSocket upgrade required',room:statusData()},{status:426})}};
